"""Named constants for companion WS bootstrap kickoff E2E."""

ENV_GATE_COMPANION_WS_BOOTSTRAP_E2E = "INTY_COMPANION_WS_BOOTSTRAP_E2E"
KICKOFF_MESSAGE_TYPE = "companion_ws_interactive_bootstrap_kickoff"
DEFAULT_RECV_TIMEOUT_SEC = 120.0
SERVER_READY_TIMEOUT_SEC = 90.0
POLL_INTERVAL_SEC = 0.5
DEFAULT_PG_HOST = "127.0.0.1"
DEFAULT_PG_PORT = 5432
