"""Materialize App WebSocket outbound completion frames (chat_history + wire JSON).

Generated by Cursor agent for !3488 AppWsChannelAdapter delivery path.
"""

from __future__ import annotations

from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.companion_harness.memory.memory_store import MemoryStore
from app.core.companion_harness.tools.image_gate import (
    generated_image_meta_from_index_slice,
)
from app.core.companion_harness.tools.tool_background import ToolOutputEvent
from app.schemas.biz_action import ActionType, BizAction
from app.schemas.chat import ChatCompletionRequest
from app.schemas.chat_websocket import (
    ChatWsCompanionWireMessageMetaData,
    dump_chat_ws_companion_wire_meta,
)
from app.schemas.response import APIResponse
from app.services import chat_history_service
from app.services.agent_status_line import agent_status_line_for_chat_header
from app.services.agentic_companion.ws_turn_support import (
    companion_ai_meta_from_queue_delivery,
    generated_image_meta_from_baseline,
)
from app.services.chat_completion_wire import (
    build_companion_ws_completion_data,
    _normalize_chat_response_content,
)
from app.services.ws_session_messages import WsOutboundPayload


async def persist_companion_user_message_for_queue_delivery(
    *,
    session_id: str,
    last_user_message: Any,
    effective_local_id: str | None,
) -> int | None:
    """Write one user row into chat_history for a queue-delivered App WS turn."""
    if effective_local_id is not None:
        return await chat_history_service.add_user_message_async(
            session_id,
            last_user_message,
            meta_data=dump_chat_ws_companion_wire_meta(
                ChatWsCompanionWireMessageMetaData(local_id=effective_local_id)
            ),
        )
    return await chat_history_service.add_user_message_async(
        session_id, last_user_message
    )


async def materialize_queue_user_reply_ws_payload(
    *,
    db: AsyncSession,
    agent_id: str,
    session_id: str,
    request: ChatCompletionRequest,
    last_user_message: Any,
    last_user_text: str,
    effective_local_id: str | None,
    text: str,
    queue_message_id: str,
    tool_background_started: bool,
    memory_store: MemoryStore | None,
    image_asset_baseline: int,
) -> WsOutboundPayload:
    """Persist chat_history and build one queue-delivered USER_REPLY completion frame."""
    assert text.strip() != ""
    assert queue_message_id != ""
    companion_user_row_id = (
        await persist_companion_user_message_for_queue_delivery(
            session_id=session_id,
            last_user_message=last_user_message,
            effective_local_id=effective_local_id,
        )
    )
    generated_image = None
    if memory_store is not None:
        generated_image = generated_image_meta_from_baseline(
            memory_store,
            image_asset_baseline,
        )
    companion_ai_meta = companion_ai_meta_from_queue_delivery(
        queue_message_id=queue_message_id,
        tool_background_started=tool_background_started,
        generated_image=generated_image,
    )
    ai_message_id = await chat_history_service.add_ai_message_sync_async(
        session_id,
        text,
        agent_id=agent_id,
        meta_data=companion_ai_meta,
    )
    latest_message_info = None
    try:
        if ai_message_id is not None:
            latest_message_info = (
                await chat_history_service.get_ai_message_info_by_id(
                    db, ai_message_id
                )
            )
    except Exception:
        latest_message_info = None
    user_message_id = companion_user_row_id
    if user_message_id is None:
        try:
            user_message_id = (
                await chat_history_service.get_latest_user_message_id(
                    db, session_id
                )
            )
        except Exception:
            user_message_id = None
    response_text_content, response_content_parts = (
        _normalize_chat_response_content(text)
    )
    completion = build_companion_ws_completion_data(
        response_text_content=response_text_content,
        response_content_parts=response_content_parts,
        last_user_text=last_user_text,
        latest_message_info=latest_message_info,
        audio_url=None,
        request=request,
        source_imate_id=request.target_imate_id,
        user_message_id=user_message_id,
        subscription_actions=None,
        client_local_id=effective_local_id,
    )
    payload = APIResponse.success(data=completion.model_dump(exclude_none=True))
    out = payload.model_dump(exclude_none=True)
    out["agent_id"] = agent_id
    out["status_line"] = await agent_status_line_for_chat_header(db, agent_id)
    return out, companion_user_row_id


async def materialize_tool_background_ws_payload(
    *,
    db: AsyncSession,
    agent_id: str,
    session_id: str,
    ev: ToolOutputEvent,
    request: ChatCompletionRequest,
    effective_local_id: str | None,
    foreground_user_message_id: int | None,
) -> WsOutboundPayload:
    """Build one TOOL_BACKGROUND completion frame for App WS outbound."""
    gi = generated_image_meta_from_index_slice(
        ev.memory_store, ev.image_asset_baseline
    )
    tb_paths: list[str] | None = (
        list(ev.local_image_paths) if ev.local_image_paths else None
    )
    sig = ev.significance_perception if ev.significance_perception else None
    meta_data = dump_chat_ws_companion_wire_meta(
        ChatWsCompanionWireMessageMetaData(
            source="tool_bg",
            trace_id=ev.trace_id or None,
            reply_to_user_msg_uuid=ev.user_msg_uuid or None,
            tool_bg_output_to_user=ev.output_to_user,
            tool_bg_generation_deliver=ev.generation_deliver,
            langsmith_trace_id=ev.langsmith_trace_id or None,
            langsmith_run_id=ev.langsmith_run_id or None,
            generated_image=gi or None,
            tool_bg_local_image_paths=tb_paths,
            significance_perception=sig,
            turn_recall=ev.turn_recall or None,
            inner_tick_activity=ev.inner_tick_activity,
        )
    )
    ai_message_id = await chat_history_service.add_ai_message_sync_async(
        session_id,
        ev.text,
        agent_id=agent_id,
        meta_data=meta_data,
    )
    latest_message_info = None
    try:
        if ai_message_id is not None:
            latest_message_info = (
                await chat_history_service.get_ai_message_info_by_id(
                    db, ai_message_id
                )
            )
    except Exception:
        latest_message_info = None
    user_message_id = foreground_user_message_id
    if user_message_id is None:
        try:
            user_message_id = (
                await chat_history_service.get_latest_user_message_id(
                    db, session_id
                )
            )
        except Exception:
            user_message_id = None
    subscription_actions = [
        BizAction(action_type=ActionType.NONE, message=""),
    ]
    completion = build_companion_ws_completion_data(
        response_text_content=ev.text,
        response_content_parts=None,
        last_user_text="",
        latest_message_info=latest_message_info,
        audio_url=None,
        request=request,
        source_imate_id=request.target_imate_id,
        user_message_id=user_message_id,
        subscription_actions=subscription_actions,
        client_local_id=effective_local_id,
    )
    payload = APIResponse.success(data=completion.model_dump(exclude_none=True))
    out = payload.model_dump(exclude_none=True)
    out["agent_id"] = agent_id
    out["status_line"] = await agent_status_line_for_chat_header(db, agent_id)
    return out
