"""Materialize App WebSocket outbound completion frames (chat_history + wire JSON).

Generated by Cursor agent for !3488 AppWsChannelAdapter delivery path.
"""

from __future__ import annotations

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.companion_harness.agent_channel.scope import AgentScope
from app.core.companion_harness.companion.models import CompanionTurnResult
from app.core.companion_harness.agentic_companion.output_queue import (
    ReadyOutputMessage,
)
from app.core.companion_harness.agentic_companion.types import InputQueueRecord
from app.core.companion_harness.tools.image_gate import (
    generated_image_meta_from_index_slice,
)
from app.core.companion_harness.tools.tool_background import ToolOutputEvent
from app.schemas.biz_action import ActionType, BizAction
from app.schemas.chat import ChatCompletionRequest
from app.schemas.chat_websocket import (
    ChatWsCompletionData,
    ChatWsCompanionWireMessageMetaData,
    ChatWsGeneratedImageMeta,
    dump_chat_ws_companion_wire_meta,
)
from app.services import chat_history_service
from app.services.agent_status_line import agent_status_line_for_chat_header
from app.services.agentic_channel.provision import resolve_chat_model_for_scope
from app.services.agentic_companion.ws_turn_support import (
    companion_ai_meta_from_queue_delivery,
    companion_ai_meta_from_turn_result,
)
from app.services.chat_completion_wire import (
    build_chat_ws_queued_success_frame,
    build_companion_ws_completion_data,
    _normalize_chat_response_content,
)
from app.services.chat_service import generate_session_id
from app.services.ws_session_messages import WsOutboundPayload


def _primary_input_record(
    input_records: tuple[InputQueueRecord, ...],
) -> InputQueueRecord:
    assert input_records
    return input_records[-1]


def _generated_image_for_wire(
    message: ReadyOutputMessage,
) -> ChatWsGeneratedImageMeta | None:
    if not message.generated_images:
        return None
    return ChatWsGeneratedImageMeta.model_validate(
        message.generated_images[-1].model_dump(exclude_none=True)
    )


async def materialize_queue_user_reply_from_durable(
    *,
    db: AsyncSession,
    scope: AgentScope,
    message: ReadyOutputMessage,
    input_records: tuple[InputQueueRecord, ...],
) -> WsOutboundPayload:
    """Build one App-WS completion from durable queue rows and scope."""
    text = message.text
    assert text.strip() != ""
    primary_input = _primary_input_record(input_records)
    user_msg_uuid = primary_input.message_id
    session_id = generate_session_id(scope.memory_store_chat_id())
    generated_image = _generated_image_for_wire(message)
    companion_ai_meta = companion_ai_meta_from_queue_delivery(
        queue_message_id=user_msg_uuid,
        tool_background_started=message.tool_background_started,
        generated_image=generated_image,
    )
    ai_message_id = await chat_history_service.add_ai_message_sync_async(
        session_id,
        text,
        agent_id=scope.agent_id,
        meta_data=companion_ai_meta,
    )
    latest_message_info = None
    try:
        if ai_message_id is not None:
            latest_message_info = (
                await chat_history_service.get_ai_message_info_by_id(
                    db, ai_message_id
                )
            )
    except Exception:
        latest_message_info = None
    response_text_content, response_content_parts = (
        _normalize_chat_response_content(text)
    )
    model = await resolve_chat_model_for_scope(scope)
    assistant = build_companion_ws_completion_data(
        response_text_content=response_text_content,
        response_content_parts=response_content_parts,
        last_user_text="",
        latest_message_info=latest_message_info,
        audio_url=None,
        request=ChatCompletionRequest(
            messages=[{"role": "user", "content": primary_input.text}],
            model=model.id_on_provider,
            message_id=user_msg_uuid,
        ),
        source_imate_id=scope.agent_id,
        user_message_id=primary_input.chat_history_user_row_id,
        subscription_actions=None,
        client_local_id=primary_input.local_id,
    )
    completion = ChatWsCompletionData(
        id=assistant.id,
        created=assistant.created,
        model=model.id_on_provider,
        user_message_id=primary_input.chat_history_user_row_id,
        business_actions=assistant.business_actions,
        choices=assistant.choices,
        usage=None,
        local_id=primary_input.local_id,
        source_imate_id=scope.agent_id,
    )
    payload = build_chat_ws_queued_success_frame(
        completion=completion,
        agent_id=scope.agent_id,
        status_line=await agent_status_line_for_chat_header(
            db,
            scope.agent_id,
        ),
    )
    return payload


async def materialize_agent_initiated_ws_payload(
    *,
    db: AsyncSession,
    scope: AgentScope,
    message: ReadyOutputMessage,
) -> WsOutboundPayload:
    """Build one App-WS completion frame for an agent-initiated OutputQueue row.

    Covers inner-tick proactive/scheduled/monolog and implicit greeting rows.
    chat_history rows are already written by the fire/turn glue; this only
    queries latest ai/user message info to fill frame correlation fields.
    """
    text = message.text
    assert text.strip() != ""
    session_id = generate_session_id(scope.memory_store_chat_id())
    latest_message_info = None
    try:
        latest_message_info = (
            await chat_history_service.get_latest_ai_message_info(
                db, session_id
            )
        )
    except Exception:
        latest_message_info = None
    user_message_id = None
    try:
        user_message_id = await chat_history_service.get_latest_user_message_id(
            db, session_id
        )
    except Exception:
        user_message_id = None
    response_text_content, response_content_parts = (
        _normalize_chat_response_content(text)
    )
    model = await resolve_chat_model_for_scope(scope)
    request = ChatCompletionRequest(
        messages=[{"role": "user", "content": text}],
        model=model.id_on_provider,
    )
    assistant = build_companion_ws_completion_data(
        response_text_content=response_text_content,
        response_content_parts=response_content_parts,
        last_user_text="",
        latest_message_info=latest_message_info,
        audio_url=None,
        request=request,
        source_imate_id=scope.agent_id,
        user_message_id=user_message_id,
        subscription_actions=None,
        client_local_id=None,
    )
    completion = ChatWsCompletionData(
        id=assistant.id,
        created=assistant.created,
        model=model.id_on_provider,
        user_message_id=user_message_id,
        business_actions=assistant.business_actions,
        choices=assistant.choices,
        usage=None,
        local_id=None,
        source_imate_id=scope.agent_id,
    )
    payload = build_chat_ws_queued_success_frame(
        completion=completion,
        agent_id=scope.agent_id,
        status_line=await agent_status_line_for_chat_header(
            db,
            scope.agent_id,
        ),
    )
    return payload


async def persist_implicit_greeting_ai_chat_history(
    *,
    session_id: str,
    agent_id: str,
    text: str,
    companion_turn: CompanionTurnResult,
) -> int | None:
    """Persist one implicit sign-on greeting assistant row before pump delivery."""
    assert text.strip() != ""
    companion_ai_meta = companion_ai_meta_from_turn_result(
        companion_turn,
        companion_scheduled_reminder=None,
        scheduled_task_id=None,
    )
    return await chat_history_service.add_ai_message_sync_async(
        session_id,
        text,
        agent_id=agent_id,
        meta_data=companion_ai_meta,
    )


async def materialize_tool_background_from_durable(
    *,
    db: AsyncSession,
    scope: AgentScope,
    message: ReadyOutputMessage,
    input_records: tuple[InputQueueRecord, ...],
) -> WsOutboundPayload:
    """Build one TOOL_BACKGROUND completion from durable OutputQueue rows."""
    assert message.text.strip() != ""
    primary_input = _primary_input_record(input_records)
    generated_image = _generated_image_for_wire(message)
    meta_data = dump_chat_ws_companion_wire_meta(
        ChatWsCompanionWireMessageMetaData(
            source="tool_bg",
            reply_to_user_msg_uuid=primary_input.message_id,
            tool_bg_output_to_user=True,
            tool_background_started=(
                True if message.tool_background_started else None
            ),
            generated_image=generated_image,
        )
    )
    session_id = generate_session_id(scope.memory_store_chat_id())
    ai_message_id = await chat_history_service.add_ai_message_sync_async(
        session_id,
        message.text,
        agent_id=scope.agent_id,
        meta_data=meta_data,
    )
    latest_message_info = None
    try:
        if ai_message_id is not None:
            latest_message_info = (
                await chat_history_service.get_ai_message_info_by_id(
                    db, ai_message_id
                )
            )
    except Exception:
        latest_message_info = None
    request = ChatCompletionRequest(
        messages=[{"role": "user", "content": primary_input.text}],
        message_id=primary_input.message_id,
    )
    assistant = build_companion_ws_completion_data(
        response_text_content=message.text,
        response_content_parts=None,
        last_user_text="",
        latest_message_info=latest_message_info,
        audio_url=None,
        request=request,
        source_imate_id=scope.agent_id,
        user_message_id=primary_input.chat_history_user_row_id,
        subscription_actions=[
            BizAction(action_type=ActionType.NONE, message="")
        ],
        client_local_id=primary_input.local_id,
    )
    completion = ChatWsCompletionData(
        id=assistant.id,
        created=assistant.created,
        model=assistant.model,
        user_message_id=primary_input.chat_history_user_row_id,
        business_actions=assistant.business_actions,
        choices=assistant.choices,
        usage=assistant.usage,
        local_id=assistant.local_id,
        source_imate_id=assistant.source_imate_id,
    )
    return build_chat_ws_queued_success_frame(
        completion=completion,
        agent_id=scope.agent_id,
        status_line=await agent_status_line_for_chat_header(
            db,
            scope.agent_id,
        ),
    )


async def materialize_tool_background_ws_payload(
    *,
    db: AsyncSession,
    agent_id: str,
    session_id: str,
    ev: ToolOutputEvent,
    request: ChatCompletionRequest,
    effective_local_id: str | None,
    foreground_user_message_id: int | None,
) -> WsOutboundPayload:
    """Build one TOOL_BACKGROUND completion frame for App WS outbound."""
    gi = generated_image_meta_from_index_slice(
        ev.memory_store, ev.image_asset_baseline
    )
    tb_paths: list[str] | None = (
        list(ev.local_image_paths) if ev.local_image_paths else None
    )
    sig = ev.significance_perception if ev.significance_perception else None
    meta_data = dump_chat_ws_companion_wire_meta(
        ChatWsCompanionWireMessageMetaData(
            source="tool_bg",
            trace_id=ev.trace_id or None,
            reply_to_user_msg_uuid=ev.user_msg_uuid or None,
            tool_bg_output_to_user=ev.output_to_user,
            tool_bg_generation_deliver=ev.generation_deliver,
            langsmith_trace_id=ev.langsmith_trace_id or None,
            langsmith_run_id=ev.langsmith_run_id or None,
            generated_image=gi or None,
            tool_bg_local_image_paths=tb_paths,
            significance_perception=sig,
            turn_recall=ev.turn_recall or None,
            inner_tick_activity=ev.inner_tick_activity,
        )
    )
    ai_message_id = await chat_history_service.add_ai_message_sync_async(
        session_id,
        ev.text,
        agent_id=agent_id,
        meta_data=meta_data,
    )
    latest_message_info = None
    try:
        if ai_message_id is not None:
            latest_message_info = (
                await chat_history_service.get_ai_message_info_by_id(
                    db, ai_message_id
                )
            )
    except Exception:
        latest_message_info = None
    user_message_id = foreground_user_message_id
    if user_message_id is None:
        try:
            user_message_id = (
                await chat_history_service.get_latest_user_message_id(
                    db, session_id
                )
            )
        except Exception:
            user_message_id = None
    subscription_actions = [
        BizAction(action_type=ActionType.NONE, message=""),
    ]
    assistant = build_companion_ws_completion_data(
        response_text_content=ev.text,
        response_content_parts=None,
        last_user_text="",
        latest_message_info=latest_message_info,
        audio_url=None,
        request=request,
        source_imate_id=request.target_imate_id,
        user_message_id=user_message_id,
        subscription_actions=subscription_actions,
        client_local_id=effective_local_id,
    )
    completion = ChatWsCompletionData(
        id=assistant.id,
        created=assistant.created,
        model=assistant.model,
        user_message_id=user_message_id,
        business_actions=assistant.business_actions,
        choices=assistant.choices,
        usage=assistant.usage,
        local_id=assistant.local_id,
        source_imate_id=assistant.source_imate_id,
    )
    payload = build_chat_ws_queued_success_frame(
        completion=completion,
        agent_id=agent_id,
        status_line=await agent_status_line_for_chat_header(db, agent_id),
    )
    return payload
