#!/usr/bin/env python3
"""Create companion harness epic (parent) issues and sub-issues on GitHub.

Requires ``gh`` CLI with ``issues:write`` on NascentCore/inty. Cloud Agent tokens
typically lack that scope; run locally or via maintainer PAT:

    uv run python .cursor/skills/scripts/create_companion_harness_issue_epics.py

Idempotent: skips creation when an open issue with the same title already exists.
"""

from __future__ import annotations

import json
import subprocess
import sys
from dataclasses import dataclass


REPO = "NascentCore/inty"
LABEL = "agentic_companion"


@dataclass(frozen=True)
class IssueSpec:
    title: str
    body: str
    children: tuple[IssueSpec, ...] = ()
    existing_refs: tuple[str, ...] = ()


def _run(args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, capture_output=True, text=True, check=False)


def _find_open_issue_by_title(title: str) -> int | None:
    r = _run(
        [
            "gh",
            "search",
            "issues",
            "--repo",
            REPO,
            f"is:issue is:open in:title {title!r}",
            "--json",
            "number,title",
            "--limit",
            "5",
        ]
    )
    if r.returncode != 0:
        return None
    for row in json.loads(r.stdout or "[]"):
        if row.get("title") == title:
            return int(row["number"])
    return None


def _create_issue(title: str, body: str) -> int:
    existing = _find_open_issue_by_title(title)
    if existing is not None:
        print(f"skip (exists): #{existing} {title}")
        return existing
    r = _run(
        [
            "gh",
            "issue",
            "create",
            "--repo",
            REPO,
            "--title",
            title,
            "--body",
            body,
            "--label",
            LABEL,
        ]
    )
    if r.returncode != 0:
        raise RuntimeError(f"gh issue create failed for {title!r}: {r.stderr.strip()}")
    url = (r.stdout or "").strip()
    number = int(url.rstrip("/").split("/")[-1])
    print(f"created: #{number} {title}")
    return number


def _render_parent_body(spec: IssueSpec, child_numbers: list[tuple[str, int]]) -> str:
    lines = [
        "> *This was generated by AI during triage.*",
        "",
        spec.body.strip(),
        "",
        "## Sub-issues",
        "",
    ]
    for label, num in child_numbers:
        lines.append(f"- [ ] #{num} — {label}")
    if spec.existing_refs:
        lines.extend(["", "## Related (pre-existing)", ""])
        for ref in spec.existing_refs:
            lines.append(f"- {ref}")
    return "\n".join(lines) + "\n"


def _render_child_body(parent_num: int, body: str) -> str:
    return "\n".join(
        [
            "> *This was generated by AI during triage.*",
            "",
            "## Parent",
            "",
            f"#{parent_num}",
            "",
            body.strip(),
            "",
        ]
    )


def _create_tree(spec: IssueSpec) -> int:
    child_links: list[tuple[str, int]] = []
    for child in spec.children:
        child_num = _create_tree(child)
        child_links.append((child.title, child_num))
    parent_body = _render_parent_body(spec, child_links)
    return _create_issue(spec.title, parent_body)


EPICS: tuple[IssueSpec, ...] = (
    IssueSpec(
        title="[Epic] Companion WebSocket transport & downlink unification",
        body="""## Goal

Converge `/api/v1/chat/ws` outbound paths on one **session downlink → outbound_queue** contract. Phase 1 Pydantic wire types landed in #3205; remaining work is routing bootstrap interim, inner-tick assistant frames, and tool-background through `WebSocketDownlink` instead of parallel consumers in `chat_ws.py`.

## Why now

Code TODOs reference #3208–#3211 but those tracker issues were never opened. Open refactor PRs (#3219, #3235) and merged splits (#3166, #3234) left duplicate outbound paths that block typed wire completion.

## Success

- One downlink consumer per WebSocket session
- Bootstrap interim + inner-tick + tool_background share materializers
- `chat_ws.py` no longer owns parallel bootstrap consumer tasks""",
        existing_refs=(
            "#3205 (merged) — Phase 1 Pydantic completion wire types",
            "#3212 (merged) — pointed TODOs at missing #3208",
            "#3219 (closed) — chat_ws package refactor tracker",
            "#3234 (merged) — removed /ws/verify",
        ),
        children=(
            IssueSpec(
                title="[Agentic companion] WS completion wire typing (Phase 2)",
                body="""## What to build

Finish Phase 2 of companion WebSocket completion typing: emit and parse `ChatWebSocketQueuedSuccessFrame` / `ChatWsCompletionData` via typed builders end-to-end (REPL, persist layer, `chat.py` meta).

## Acceptance criteria

- [ ] `chat_ws.py` emits typed queued-success frames (no ad-hoc dict assembly)
- [ ] `chat_history_service` returns typed persisted assistant row
- [ ] `chat.py` HTTP/WS meta uses `ChatWsCompanionWireMessageMetaData`
- [ ] Tests cover round-trip for success + error completion paths

## Blocked by

None — Phase 1 types exist (#3205).""",
            ),
            IssueSpec(
                title="[Agentic companion] Bootstrap interim via WebSocketDownlink",
                body="""## What to build

Route bootstrap interim rounds through `WebSocketDownlink` (`DownlinkKind.BOOTSTRAP_INTERIM`) instead of `CompanionWebSocketCoordinator.bootstrap_interim_queued_events` + parallel consumer in `chat_ws.py`.

## Acceptance criteria

- [ ] `WebSocketDownlink.deliver` handles bootstrap interim materialization
- [ ] Session downlink replaces coordinator-side bootstrap queue wiring
- [ ] REPL bootstrap smoke unchanged; no duplicate bootstrap consumer task

## Blocked by

None — can start in parallel with inner-tick downlink slice.""",
            ),
            IssueSpec(
                title="[Agentic companion] Inner-tick assistant frames via WebSocketDownlink",
                body="""## What to build

Deliver proactive / scheduled / maintenance / user-reply inner-tick assistant frames via `WebSocketDownlink` and `inner_tick_delivery`, not raw `outbound_queue.put`.

## Acceptance criteria

- [ ] `DownlinkKind` covers USER_REPLY, PROACTIVE, SCHEDULED, MAINTENANCE paths used in production
- [ ] `inner_tick_fire` / `deliver_inner_tick_assistant` enqueue through downlink adapter
- [ ] LangSmith + REPL metadata unchanged for inner-tick labels

## Blocked by

None — can start in parallel with bootstrap downlink slice.""",
            ),
            IssueSpec(
                title="[Agentic companion] Single session downlink consumer (presence)",
                body="""## What to build

One **session-level** downlink consumer per WebSocket presence: collapse coordinator queue + bootstrap task + inner-tick raw puts into the session `WebSocketDownlink` pump contract.

## Acceptance criteria

- [ ] Exactly one outbound materialization path per connection (documented in `session.py`)
- [ ] `chat_ws.py` drops extra bootstrap consumer task
- [ ] Head-of-line behavior unchanged for user-visible chat frames

## Blocked by

- Bootstrap interim via WebSocketDownlink
- Inner-tick assistant frames via WebSocketDownlink""",
            ),
        ),
    ),
    IssueSpec(
        title="[Epic] Companion WebSocket concurrency & turn scheduling",
        body="""## Goal

Fix **head-of-line blocking** and **user barge-in** on `/api/v1/chat/ws`: decouple read loop from whole-turn await, recover from hung `tool_background`, and let rapid user messages supersede in-flight turns with partial stream capture.

## Why now

#3105 documented turn_lock + tool_bg_idle HoL; code references #3113–#3115 but those issues were never filed. User rapid-message supersede spec exists in `.agents/work_logs/2026-05-17/github-issue-user-rapid-message-supersede-body.md` without a tracker.

## Success

- User chat not blocked for minutes behind maintenance / dead tool_bg
- Rapid user messages cancel prior inflight turn; partial assistant text flows into next turn context
- CI-stable WebSocket teardown (#3253)""",
        existing_refs=(
            "#3105 (merged) — HoL analysis + REPL greeting observability",
            "#3102 (merged) — foreground/background glossary",
            "#1687 (closed) — historical barge-in spec (confirm product alignment)",
            ".agents/work_logs/2026-05-17/companion-ws-turn-lock-head-of-line-blocking-analysis.md",
        ),
        children=(
            IssueSpec(
                title="[Agentic companion] Decouple WS read loop from chat turn await",
                body="""## What to build

Allow the WebSocket receive loop to accept new user frames while a companion turn is in flight — prerequisite for barge-in and lower HoL from inner-tick holding `turn_lock`.

## Acceptance criteria

- [ ] Read loop no longer blocks on full `_agent_chat_completions_impl` await inside `turn_lock` for every frame type
- [ ] Turn lifecycle documented: which events still require lock vs can pipeline
- [ ] Regression test: inner-tick + user chat interleaving without multi-minute stall

## Blocked by

None — design aligns with #3105 follow-ups.""",
            ),
            IssueSpec(
                title="[Agentic companion] Hung turn & tool_bg_idle recovery",
                body="""## What to build

When `tool_bg_idle` wait exceeds budget or tool_background JSON fails repeatedly, force scope idle, isolate zombie tool thread, and release `turn_lock` so user chat can proceed.

## Acceptance criteria

- [ ] Configured timeout marks event idle safely (not infinite re-wait next turn)
- [ ] Failed tool model JSON completes parent trace within bounded time
- [ ] Observability: log/metric when recovery path fires

## Blocked by

None.""",
            ),
            IssueSpec(
                title="[Agentic companion] User rapid-message supersede (partial stream)",
                body="""## What to build

When user sends a new chat before prior user-turn completes: cancel inflight turn, capture partial assistant stream into transcript/context, reply only to latest message (extends #1687 barge-in for companion WS).

## Acceptance criteria

- [ ] Two rapid user messages → one final assistant reply; first turn partial visible in context
- [ ] Third message before second completes → same supersede semantics
- [ ] `mark_tool_background_aborted` wired for superseded `user_msg_uuid` on production WS

## Blocked by

- Decouple WS read loop from chat turn await""",
            ),
            IssueSpec(
                title="[Agentic companion] Stabilize WS inner-tick teardown in backend CI",
                body="""## What to build

Fix flaky `test_chat_websocket_companion_inner_tick_scheduled_when_coords_disarmed`: explicit WebSocket close before TestClient context exit when inner-tick worker teardown overlaps session close (#3253).

## Acceptance criteria

- [ ] 20+ consecutive passes of adjacent WS inner-tick tests
- [ ] Full `tests/app/api/v1/endpoints/test_chat.py` green in CI

## Blocked by

None — links existing open PR #3250 dreaming coordination if touching same tests.""",
            ),
        ),
    ),
    IssueSpec(
        title="[Epic] Companion inner-tick autonomy & subjective time",
        body="""## Goal

Ship **AUTONOMY** inner-tick track (`LIFE_CURRENTS.md`), **dreaming** memory consolidation with official-helper gating, and presence-less subjective clock — so Inty has observable off-screen life without spamming the user.

## Why now

#3224 (open) tracks AUTONOMY slices 2–5; #3250 (open) coordinates dreaming vs user chat; #3239 closed without merge tracks offline maintenance heartbeat concept.

## Success

- AUTONOMY runs in unified worker between proactive and maintenance
- Dreaming once-per-UTC-day with activity gate; user sees official helper while sleeping
- Documented min_gap / turn_lock interaction per AUTONOMY.md""",
        existing_refs=(
            "#3224 (open PR) — AUTONOMY + LIFE_CURRENTS slice 1 landed",
            "#3250 (open PR) — dreaming + official helper",
            "#3222 (merged) — dreaming scheduler",
            "#3220 (merged) — AUTONOMY design doc",
            "docs/companion_harness/AUTONOMY.md",
        ),
        children=(
            IssueSpec(
                title="[Agentic companion] AUTONOMY track kernel (slices 2–3)",
                body="""## What to build

Land AUTONOMY slices 2–3 from AUTONOMY.md: `InnerTickActivity.AUTONOMY`, turn track, `run_inner_tick_autonomy`, dedicated open tool set (chat tools minus schedule/profile).

## Acceptance criteria

- [ ] Worker schedules autonomy between proactive and maintenance with own min_gap
- [ ] LangSmith lane + turn_track translation for AUTONOMY
- [ ] No user-visible downlink from autonomy turns

## Blocked by

#3224 slice 1 (LIFE_CURRENTS allowlist) — merged on main.""",
            ),
            IssueSpec(
                title="[Agentic companion] AUTONOMY worker integration & PROACTIVE_CHAT injection",
                body="""## What to build

Unified inner-tick worker inserts autonomy; PROACTIVE_CHAT system stack injects LIFE_CURRENTS.md with anti-self-advertise guardrails (AUTONOMY slices 4–5).

## Acceptance criteria

- [ ] Scheduled → proactive → autonomy → maintenance order in worker
- [ ] PROACTIVE_CHAT reads LIFE_CURRENTS; USER_CHAT path unchanged (MVP)
- [ ] Integration test: autonomy write → next proactive references state naturally

## Blocked by

- AUTONOMY track kernel (slices 2–3)""",
            ),
            IssueSpec(
                title="[Agentic companion] Dreaming activity gate & official helper replies",
                body="""## What to build

Per-scope activity gate: while dreaming, user chat short-circuits to official helper with `officialHelperReason`; dreaming once per UTC day; awake turns wait for dreaming checkpoint.

## Acceptance criteria

- [ ] User chat during dreaming returns non-persona official helper copy
- [ ] HTTP/WS meta includes `officialHelperReason`
- [ ] No duplicate dreaming same UTC day after successful checkpoint

## Blocked by

None — tracks open PR #3250.""",
            ),
            IssueSpec(
                title="[Agentic companion] Offline maintenance heartbeat (presence-less clock)",
                body="""## What to build

Allow maintenance inner-tick (or subjective clock) to advance companion state when user has no active WebSocket — bounded, observable, no user-visible spam.

## Acceptance criteria

- [ ] Documented scope: which tracks run offline vs require presence
- [ ] Safe against duplicate work when user reconnects
- [ ] Config + tests for at least one offline tick path

## Blocked by

- AUTONOMY worker integration (shared worker semantics)""",
            ),
        ),
    ),
    IssueSpec(
        title="[Epic] Companion memory, feedback & user model",
        body="""## Goal

Close the loop on **how Inty learns about the user**: structured companion user model, cross-session feedback store, tool_background envelope parity, and LLM no-output degradation.

## Why now

#3237 (open) implements `record_user_feedback`; gap analysis in `docs/companion_harness/todos/COMPANION_HARNESS_USER_MODEL.md` lacks trackers; tool_background dual-envelope TODO is untracked.

## Success

- Feedback rows queryable with repro context (trace_id, quotes)
- Documented companion user model boundary vs ORM User / USER.md
- Provider reasoning-channel envelopes parsed uniformly in tool_background""",
        existing_refs=(
            "#3237 (open PR) — record_user_feedback tool + table",
            "docs/companion_harness/todos/COMPANION_HARNESS_USER_MODEL.md",
            ".agents/maintenance/P2_USER_TIME_CONTEXT_TIMEZONE_INFERENCE.md",
        ),
        children=(
            IssueSpec(
                title="[Agentic companion] record_user_feedback maintenance tool",
                body="""## What to build

Merge maintenance-track `record_user_feedback` tool: infer cross-message user feedback during inner-tick maintenance, persist to `companion_user_feedback` with repro context.

## Acceptance criteria

- [ ] Tool in INNER_TICK_TOOL_NAMES only (not user-chat tail)
- [ ] Alembic migration + ORM registered via recursive model load
- [ ] Tests for record builder + tool definition placement

## Blocked by

None — implementation in open PR #3237.""",
            ),
            IssueSpec(
                title="[Agentic companion] Companion user model schema & update contract",
                body="""## What to build

Define **伴侣用户模型** data boundary: fields, confidence, update sources (explicit user, implicit signals, memory extraction), alignment with USER.md and MemoryStore.

## Acceptance criteria

- [ ] FR or ARCH section with field list and read/write paths
- [ ] Terminology fixed in companion AGENTS.md (User Model vs ORM User)
- [ ] No new persistence until schema reviewed (HITL gate)

## Blocked by

None — design-first slice.""",
            ),
            IssueSpec(
                title="[Agentic companion] tool_background dual-envelope (reasoning channel) parity",
                body="""## What to build

Unify tool_background completion parsing when providers put structured envelope in `reasoning` / `reasoning_details` with empty `content` — match foreground `tool_bg_routing.py` behavior.

## Acceptance criteria

- [ ] Same envelope extracted regardless of provider channel
- [ ] Regression test with fixture mimicking reasoning-only completion
- [ ] No silent empty tool rounds in LangSmith for supported providers

## Blocked by

None.""",
            ),
            IssueSpec(
                title="[Agentic companion] LLM no-output reproduction & degradation",
                body="""## What to build

When companion LLM returns empty content: bounded retry, user-visible fallback, observability fields — close known gap from COMPANION_HARNESS_USER_MODEL.md.

## Acceptance criteria

- [ ] Documented repro steps for at least one provider path
- [ ] Degradation path does not hang turn_lock
- [ ] meta_data / logs flag `no_output` events

## Blocked by

None.""",
            ),
        ),
    ),
    IssueSpec(
        title="[Epic] Companion harness — paused / non-mainline capabilities",
        body="""## Goal

Park **non-text-mainline** companion features under one epic so open paused PRs do not clutter the active backlog. Reactivate only when product prioritizes.

## Why now

#3142 (BGM) and #3122 (DEBUG runtime inspect) are open with 【暂停】 prefixes; no parent tracker explains deferral rationale.

## Success

- Clear paused status + out-of-scope criteria
- Sub-issues linked; no accidental pickup by AFK agents without explicit un-pause""",
        existing_refs=(
            "#3142 (open, paused) — conversation BGM / set_bgm",
            "#3122 (open, paused) — DEBUG runtime inspect zip export",
        ),
        children=(
            IssueSpec(
                title="[Agentic companion][paused] Conversation BGM via set_bgm",
                body="""## What to build

(Paused — not on text-chat mainline.) tool_background `set_bgm` + WS control frame + static catalog — see open PR #3142.

## Acceptance criteria

- [ ] Product confirms iMate client playback contract
- [ ] Un-pause label removed from epic when scheduled

## Blocked by

Product prioritization — do not start until epic owner un-pauses.""",
            ),
            IssueSpec(
                title="[Agentic companion][paused] DEBUG runtime inspect zip export",
                body="""## What to build

(Paused — complexity vs value.) Gate `companion_runtime_inspect` behind INTY_RUNTIME_MODE=DEBUG — see open PR #3122.

## Acceptance criteria

- [ ] Ops PROD never exposes inspect tool
- [ ] DEBUG REPL writes zip under INTY_OPS_WORKSPACE

## Blocked by

Product/engineering decision to un-pause.""",
            ),
        ),
    ),
)


def main() -> int:
    dry_run = "--dry-run" in sys.argv
    print(f"Creating companion harness epics on {REPO} (label={LABEL})")
    if dry_run:
        print("DRY RUN — no GitHub writes")
    created: list[int] = []
    for epic in EPICS:
        if dry_run:
            print(f"\n=== {epic.title} ===")
            print(epic.body[:200], "...")
            for child in epic.children:
                print(f"  - {child.title}")
            for ref in epic.existing_refs:
                print(f"  related: {ref}")
            created.append(-1)
            continue
        parent_num = _create_issue(
            epic.title,
            _render_parent_body(epic, []),
        )
        child_links: list[tuple[str, int]] = []
        for child in epic.children:
            child_body = _render_child_body(parent_num, child.body)
            child_num = _create_issue(child.title, child_body)
            child_links.append((child.title, child_num))
        updated_body = _render_parent_body(epic, child_links)
        _run(
            [
                "gh",
                "issue",
                "edit",
                str(parent_num),
                "--repo",
                REPO,
                "--body",
                updated_body,
            ]
        )
        created.append(parent_num)
        print(f"epic #{parent_num} linked {len(child_links)} sub-issues")
    print(f"done: {len(created)} epics")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
