services:
  inty-server:
    # animeface pip install failed on arm64, so we use amd64 here.
    # Mac uses VM to run docker, so this wont affect running on Mac.
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "8000:8000"
    volumes:
      # Mount code to enable hot reload.
      - ./app:/app
      - ./config.yaml:/config.yaml
      - ./alembic:/alembic
      - ./alembic.ini:/alembic.ini
      - ./.secrets:/.secrets
      - ./start.sh:/start.sh
      - ./scripts:/scripts
    depends_on:
      pgvector:
        condition: service_healthy
    command: ["/start.sh", "--dev"]
    networks:
      - inty-network
    # This does not work on mac, as docker runs container in a vm.
    # The host networking is winthin that VM not the mac.
    # network_mode: host

  pgvector:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sxwl666!
      - POSTGRES_DB=inty
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inty-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inty"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  inty-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
