version: '3.8'

services:
  inty-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./inty-backend-key.json:/app/inty-backend-key.json
      - ./inty-firebase-key.json:/app/inty-firebase-key.json
    environment:
      - DATABASE_URL=postgresql://postgres:sxwl666!@pgvector:5432/inty_db
    depends_on:
      - pgvector
    networks:
      - inty-network

  pgvector:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sxwl666!
      - POSTGRES_DB=inty_db
    networks:
      - inty-network

networks:
  inty-network:
    driver: bridge
