# Debug signing config
debug.storeFile=sign/intellimate-release-key.jks
debug.storePassword=com.ai.intellimate
debug.keyAlias=intellimate-key-alias
debug.keyPassword=com.ai.intellimate

# Release signing config
release.storeFile=sign/intellimate-release-key.jks
release.storePassword=com.ai.intellimate
release.keyAlias=intellimate-key-alias
release.keyPassword=com.ai.intellimate
