storeFile=sign/intellimate-release-key.jks
storePassword=com.ai.intellimate

# Debug signing config
dev.keyAlias=dev
dev.keyPassword=intellimate

# Release signing config
release.keyAlias=intellimate-key-alias
release.keyPassword=com.ai.intellimate
