[pytest]
pythonpath = .
testpaths = app tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    -v
    --tb=short
    -s
    --strict-markers
    --disable-warnings
    -m "not noci"
    # 测试实际运行的后端服务，消耗较大，默认忽略。
    --ignore=tests/app/api/v1/endpoints
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
    unit: marks tests as unit tests
    noci: marks tests that should not run in CI
    asyncio: marks tests as asyncio tests
asyncio_mode = auto
# For tests that use db_session fixture, for example test_agent_service.py.
# We need to set this to function to ensure the db_session fixture is created for each test.
asyncio_default_fixture_loop_scope = function
