"""
ElevenLabs API 相关代码
"""

MALE_DEFAULT_VOICE_ID = "JBFqnCBsd6RMkjVDRZzb"
FEMALE_DEFAULT_VOICE_ID = "EXAVITQu4vr4xnSDxMaL"
NON_BINARY_DEFAULT_VOICE_ID = "ThT5KcBeYPX3keUQqHPh"
# TODO: 从ElevenLabs API获取voice ID元数据
