"""App WebSocket channel adapter: OutputQueue USER_REPLY + direct inner-tick delivery.

Generated by Cursor agent for !3488.
"""

from __future__ import annotations

import asyncio
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.companion_harness.agent_channel.scope import AgentScope
from app.core.companion_harness.companion.runtime_channel import (
    CompanionRuntimeChannel,
)
from app.core.companion_harness.memory.memory_store import MemoryStore
from app.schemas.chat import ChatCompletionRequest
from app.services.agentic_channel.scope_queue_serving import (
    ScopeDrainCompletion,
)
from app.services.agentic_companion.downlink import (
    ChannelDownlink,
    Downlink,
    DownlinkKind,
    downlink_delivers_user_visible_text,
)
from app.services.agentic_companion.inner_tick_delivery import (
    InnerTickDelivery,
    inner_tick_delivery_for_ws,
)
from app.services.agentic_companion.ws_outbound_materialize import (
    materialize_queue_user_reply_ws_payload,
    materialize_tool_background_ws_payload,
)
from app.services.ws_session_messages import WsOutboundPayload


@dataclass
class AppWsTurnContext:
    """Per inbound user-message context for queue-delivered App WS completions."""

    db: AsyncSession
    session_id: str
    agent_id: str
    chat_id: str
    request: ChatCompletionRequest
    last_user_message: Any
    last_user_text: str
    effective_local_id: str | None
    client_message_id: str | None
    image_asset_baseline: int = 0
    memory_store: MemoryStore | None = None
    queue_message_id: str = ""
    tool_background_started: bool = False
    foreground_user_message_id: int | None = None


class AppWsChannelAdapter:
    """Materialize queue-delivered replies and inner-tick frames onto one WS outbound queue."""

    def __init__(
        self,
        *,
        scope: AgentScope,
        outbound_queue: asyncio.Queue[WsOutboundPayload],
        db: AsyncSession,
        foreground_ctx_lookup: Callable[[str], dict[str, Any] | None],
    ) -> None:
        assert scope is not None
        assert outbound_queue is not None
        assert db is not None
        assert foreground_ctx_lookup is not None
        self._scope = scope
        self._outbound_queue = outbound_queue
        self._db = db
        self._foreground_ctx_lookup = foreground_ctx_lookup
        self._turn_contexts: dict[str, AppWsTurnContext] = {}

    @property
    def channel(self) -> CompanionRuntimeChannel:
        return CompanionRuntimeChannel.APP

    def register_turn_context(
        self,
        ctx: AppWsTurnContext,
        *,
        client_message_id: str | None,
    ) -> None:
        assert ctx.queue_message_id != ""
        self._turn_contexts[ctx.queue_message_id] = ctx
        if client_message_id is not None and client_message_id != "":
            self._turn_contexts[client_message_id] = ctx

    def bind_queue_message_id(
        self,
        *,
        client_message_id: str | None,
        queue_message_id: str,
    ) -> None:
        assert queue_message_id != ""
        ctx = None
        if client_message_id is not None and client_message_id != "":
            ctx = self._turn_contexts.get(client_message_id)
        if ctx is None:
            ctx = self._turn_contexts.get(queue_message_id)
        if ctx is None:
            return
        ctx.queue_message_id = queue_message_id
        self._turn_contexts[queue_message_id] = ctx

    def on_queue_drain_complete(self, completion: ScopeDrainCompletion) -> None:
        input_message_ids = completion.input_message_ids
        assert input_message_ids
        if completion.tool_background_started:
            primary_message_id = input_message_ids[-1]
            for message_id in input_message_ids:
                ctx = self._turn_contexts.get(message_id)
                if ctx is None:
                    continue
                ctx.tool_background_started = True
                if message_id != primary_message_id:
                    self._drop_turn_aliases(
                        ctx, drop_client=True, drop_queue=True
                    )
                else:
                    self._drop_turn_aliases(
                        ctx, drop_client=True, drop_queue=False
                    )
            return
        for message_id in input_message_ids:
            ctx = self._turn_contexts.get(message_id)
            if ctx is None:
                continue
            ctx.tool_background_started = False
            self._drop_turn_aliases(ctx, drop_client=True, drop_queue=True)

    def _drop_turn_aliases(
        self,
        ctx: AppWsTurnContext,
        *,
        drop_client: bool,
        drop_queue: bool,
    ) -> None:
        if drop_client and ctx.client_message_id is not None:
            self._turn_contexts.pop(ctx.client_message_id, None)
        if drop_queue and ctx.queue_message_id:
            self._turn_contexts.pop(ctx.queue_message_id, None)

    def _lookup_turn_context(
        self, message_ids: tuple[str, ...]
    ) -> AppWsTurnContext | None:
        for message_id in message_ids:
            ctx = self._turn_contexts.get(message_id)
            if ctx is not None:
                return ctx
        return None

    def as_downlink(self) -> ChannelDownlink:
        return _AppWsChannelDownlink(adapter=self)

    def inner_tick_delivery(self) -> InnerTickDelivery:
        return inner_tick_delivery_for_ws(self._outbound_queue)

    async def on_turn_up(self, scope: AgentScope) -> None:
        assert scope is not None

    async def on_turn_down(self, scope: AgentScope) -> None:
        assert scope is not None
        self._turn_contexts.clear()


class _AppWsChannelDownlink:
    """Deliver USER_REPLY (from OutputQueue) and TOOL_BACKGROUND on App WS."""

    def __init__(self, *, adapter: AppWsChannelAdapter) -> None:
        self._adapter = adapter

    async def deliver(self, event: Downlink) -> None:
        if not downlink_delivers_user_visible_text(event):
            return
        match event.kind:
            case DownlinkKind.USER_REPLY:
                await self._deliver_user_reply(event)
            case DownlinkKind.TOOL_BACKGROUND:
                await self._deliver_tool_background(event)
            case _:
                return

    async def _deliver_user_reply(self, event: Downlink) -> None:
        ctx = self._adapter._lookup_turn_context(event.message_ids)
        assert ctx is not None
        payload, companion_user_row_id = (
            await materialize_queue_user_reply_ws_payload(
                db=ctx.db,
                agent_id=ctx.agent_id,
                session_id=ctx.session_id,
                request=ctx.request,
                last_user_message=ctx.last_user_message,
                last_user_text=ctx.last_user_text,
                effective_local_id=ctx.effective_local_id,
                text=event.assistant_text,
                queue_message_id=ctx.queue_message_id,
                tool_background_started=ctx.tool_background_started,
                memory_store=ctx.memory_store,
                image_asset_baseline=ctx.image_asset_baseline,
            )
        )
        ctx.foreground_user_message_id = companion_user_row_id
        if ctx.client_message_id is not None:
            pending_ctx = self._adapter._foreground_ctx_lookup(
                ctx.client_message_id
            )
            if pending_ctx is not None:
                pending_ctx["foreground_user_message_id"] = (
                    companion_user_row_id
                )
        await self._adapter._outbound_queue.put(payload)

    async def _deliver_tool_background(self, event: Downlink) -> None:
        tool_output = event.tool_output
        assert tool_output is not None
        ctx = self._adapter._foreground_ctx_lookup(tool_output.user_msg_uuid)
        assert ctx is not None
        payload = await materialize_tool_background_ws_payload(
            db=self._adapter._db,
            agent_id=str(ctx["agent_id"]),
            session_id=str(ctx["session_id"]),
            ev=tool_output,
            request=ctx["request"],
            effective_local_id=ctx.get("effective_local_id"),
            foreground_user_message_id=ctx.get("foreground_user_message_id"),
        )
        await self._adapter._outbound_queue.put(payload)
