"""remove id column from resources table

Revision ID: 62b632b916ef
Revises: c1bbefc9d885
Create Date: 2025-09-26 07:11:30.105213+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b632b916ef'
down_revision: Union[str, None] = 'c1bbefc9d885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.create_index(op.f('ix_resources_url'), 'resources', ['url'], unique=False)
    op.drop_column('resources', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_resources_url'), table_name='resources')
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.alter_column('resources', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
