"""remove uniqueness of googld_id, email from users table

Revision ID: 21e4b8876411
Revises: 20250808_080000
Create Date: 2025-08-24 06:48:27.193480+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21e4b8876411'
down_revision: Union[str, None] = '20250808_080000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chat_history_session_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_user_deletion_logs_created_at'), table_name='user_deletion_logs')
    op.drop_index(op.f('ix_user_deletion_logs_user_id'), table_name='user_deletion_logs')
    op.drop_table('user_deletion_logs')
    op.drop_index(op.f('store_vectors_embedding_idx'), table_name='store_vectors', postgresql_using='hnsw')
    op.drop_table('store_vectors')
    op.drop_table('store_migrations')
    op.drop_table('vector_migrations')
    op.drop_index(op.f('idx_store_expires_at'), table_name='store', postgresql_where='(expires_at IS NOT NULL)')
    op.drop_index(op.f('store_prefix_idx'), table_name='store')
    op.drop_table('store')
    op.alter_column('chat_settings', 'premium_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='高级模式开关，仅订阅用户可设置')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment='邮箱地址',
               existing_comment='邮箱地址，唯一，用于登录',
               existing_nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_google_id_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_google_id_key'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment='邮箱地址，唯一，用于登录',
               existing_comment='邮箱地址',
               existing_nullable=True)
    op.alter_column('chat_settings', 'premium_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='高级模式开关，仅订阅用户可设置')
    op.create_table('store',
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ttl_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prefix', 'key', name='store_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('store_prefix_idx'), 'store', ['prefix'], unique=False)
    op.create_index(op.f('idx_store_expires_at'), 'store', ['expires_at'], unique=False, postgresql_where='(expires_at IS NOT NULL)')
    op.create_table('vector_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('vector_migrations_pkey'))
    )
    op.create_table('store_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('store_migrations_pkey'))
    )
    op.create_table('store_vectors',
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prefix', 'key'], ['store.prefix', 'store.key'], name=op.f('store_vectors_prefix_key_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prefix', 'key', 'field_name', name=op.f('store_vectors_pkey'))
    )
    op.create_index(op.f('store_vectors_embedding_idx'), 'store_vectors', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_table('user_deletion_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='删除日志ID'),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='被删除的用户ID'),
    sa.Column('original_user_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='原始用户数据快照'),
    sa.Column('deletion_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='删除原因'),
    sa.Column('deletion_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='删除类型：user_requested, admin_deletion, compliance'),
    sa.Column('anonymized_fields', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True, comment='已匿名化的字段列表'),
    sa.Column('subscription_status_at_deletion', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='删除时订阅状态'),
    sa.Column('related_data_action', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='关联数据处理方式'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='日志创建时间'),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='处理完成时间'),
    sa.Column('processor_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='处理者ID（用户本人或管理员）'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_deletion_logs_pkey'))
    )
    op.create_index(op.f('ix_user_deletion_logs_user_id'), 'user_deletion_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_deletion_logs_created_at'), 'user_deletion_logs', ['created_at'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_history_pkey'))
    )
    op.create_index(op.f('idx_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    # ### end Alembic commands ###
