"""add sys_pmt_mode (enum str) to chat_settings

Revision ID: e72c997430ea
Revises: 5e2d9282c49c
Create Date: 2025-09-12 11:34:24.592341+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72c997430ea'
down_revision: Union[str, None] = '5e2d9282c49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chat_history_session_id'), table_name='chat_history')
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.add_column('chat_settings', sa.Column('sys_pmt_mode', sa.Enum('STATIC', 'FILL_MISSING', 'OVERRIDE', name='sys_pmt_mode'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_settings', 'sys_pmt_mode')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.create_index(op.f('idx_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    # ### end Alembic commands ###
