"""add_name_column_to_chats_table

Revision ID: 152c8eba60ff
Revises: 5e2d9282c49c
Create Date: 2025-09-13 03:41:23.585078+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '152c8eba60ff'
down_revision: Union[str, None] = '5e2d9282c49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chat_history_session_id'), table_name='chat_history')
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.add_column('chats', sa.Column('name', sa.String(), nullable=True, comment='Chat name'))
    op.add_column('chats', sa.Column('system_messages', postgresql.ARRAY(sa.String()), nullable=True, comment='System messages to be used for the chat'))
    op.alter_column('chats', 'user_id',
               existing_type=sa.VARCHAR(),
               comment='The ID of the user',
               existing_nullable=False)
    op.alter_column('chats', 'agent_id',
               existing_type=sa.VARCHAR(),
               comment='The ID of the agent chatting with the user',
               existing_nullable=False)
    op.drop_column('chats', 'debug_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('debug_messages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='最新一次发送给大模型的完整messages列表（JSON格式）'))
    op.alter_column('chats', 'agent_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='The ID of the agent chatting with the user',
               existing_nullable=False)
    op.alter_column('chats', 'user_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='The ID of the user',
               existing_nullable=False)
    op.drop_column('chats', 'system_messages')
    op.drop_column('chats', 'name')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.create_index(op.f('idx_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    # ### end Alembic commands ###
