"""create notification tables

Revision ID: 37c500eb8e24
Revises: 20250606_120000
Create Date: 2025-06-10 06:53:42.284178+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "37c500eb8e24"
down_revision: Union[str, None] = "20250606_120000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("image_urls", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("link_urls", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_templates_is_active",
        "notification_templates",
        ["is_active"],
        unique=False,
    )

    op.create_table(
        "user_notifications",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column(
            "dynamic_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("rendered_content", sa.Text(), nullable=False),
        sa.Column("image_urls", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("link_urls", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["template_id"], ["notification_templates.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_notifications_user_id", "user_notifications", ["user_id"], unique=False
    )
    op.create_index(
        "ix_user_notifications_template_id",
        "user_notifications",
        ["template_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_notifications_is_read", "user_notifications", ["is_read"], unique=False
    )
    op.create_index(
        "ix_user_notifications_deleted_at",
        "user_notifications",
        ["deleted_at"],
        postgresql_where=sa.text("deleted_at IS NOT NULL"),
        unique=False,
    )
    op.create_index(
        "ix_user_notifications_user_read",
        "user_notifications",
        ["user_id", "is_read"],
        unique=False,
    )
    op.create_index(
        "ix_user_notifications_user_created",
        "user_notifications",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_notifications_user_created", table_name="user_notifications")
    op.drop_index("ix_user_notifications_user_read", table_name="user_notifications")
    op.drop_index("ix_user_notifications_deleted_at", table_name="user_notifications")
    op.drop_index("ix_user_notifications_is_read", table_name="user_notifications")
    op.drop_index("ix_user_notifications_template_id", table_name="user_notifications")
    op.drop_index("ix_user_notifications_user_id", table_name="user_notifications")
    op.drop_table("user_notifications")
    op.drop_index(
        "ix_notification_templates_is_active", table_name="notification_templates"
    )
    op.drop_table("notification_templates")
    # ### end Alembic commands ###
