"""add deleted_at to chats

Revision ID: 3d1e98fdb42c
Revises: 20250808_080000
Create Date: 2025-08-24 05:48:55.180939+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d1e98fdb42c'
down_revision: Union[str, None] = '20250808_080000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_deletion_logs_created_at'), table_name='user_deletion_logs')
    op.drop_index(op.f('ix_user_deletion_logs_user_id'), table_name='user_deletion_logs')
    op.drop_table('user_deletion_logs')
    op.alter_column('chat_settings', 'premium_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='高级模式开关，仅订阅用户可设置')
    op.add_column('chats', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('uq_chats_user_agent_active'), table_name='chats', postgresql_where='(is_active = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_chats_user_agent_active'), 'chats', ['user_id', 'agent_id'], unique=True, postgresql_where='(is_active = true)')
    op.drop_column('chats', 'deleted_at')
    op.alter_column('chat_settings', 'premium_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='高级模式开关，仅订阅用户可设置')
    op.create_table('user_deletion_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='删除日志ID'),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='被删除的用户ID'),
    sa.Column('original_user_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='原始用户数据快照'),
    sa.Column('deletion_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='删除原因'),
    sa.Column('deletion_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='删除类型：user_requested, admin_deletion, compliance'),
    sa.Column('anonymized_fields', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True, comment='已匿名化的字段列表'),
    sa.Column('subscription_status_at_deletion', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='删除时订阅状态'),
    sa.Column('related_data_action', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='关联数据处理方式'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='日志创建时间'),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='处理完成时间'),
    sa.Column('processor_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='处理者ID（用户本人或管理员）'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_deletion_logs_pkey'))
    )
    op.create_index(op.f('ix_user_deletion_logs_user_id'), 'user_deletion_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_deletion_logs_created_at'), 'user_deletion_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
