"""add_opening_audio_url_to_agents

Revision ID: ab7f71ad458d
Revises: 75796d073cb2
Create Date: 2025-09-09 07:15:51.549799+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7f71ad458d'
down_revision: Union[str, None] = '75796d073cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('opening_audio_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'opening_audio_url')
    # ### end Alembic commands ###
