"""test autogenerate after system settings

Revision ID: f95b9692f57d
Revises: aaedca782151
Create Date: 2025-08-05 00:54:46.441448+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f95b9692f57d'
down_revision: Union[str, None] = 'aaedca782151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_cache_content_hash'), 'voice_cache', ['content_hash'], unique=True)
    op.create_index(op.f('ix_voice_cache_id'), 'voice_cache', ['id'], unique=False)
    op.drop_index(op.f('store_vectors_embedding_idx'), table_name='store_vectors', postgresql_using='hnsw')
    op.drop_table('store_vectors')
    op.drop_index(op.f('idx_store_expires_at'), table_name='store', postgresql_where='(expires_at IS NOT NULL)')
    op.drop_index(op.f('store_prefix_idx'), table_name='store')
    op.drop_table('store')
    op.drop_index(op.f('idx_chat_history_session_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_table('vector_migrations')
    op.drop_table('store_migrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('store_migrations_pkey'))
    )
    op.create_table('vector_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('vector_migrations_pkey'))
    )
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_history_pkey'))
    )
    op.create_index(op.f('idx_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.create_table('store',
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ttl_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prefix', 'key', name='store_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('store_prefix_idx'), 'store', ['prefix'], unique=False)
    op.create_index(op.f('idx_store_expires_at'), 'store', ['expires_at'], unique=False, postgresql_where='(expires_at IS NOT NULL)')
    op.create_table('store_vectors',
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prefix', 'key'], ['store.prefix', 'store.key'], name=op.f('store_vectors_prefix_key_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prefix', 'key', 'field_name', name=op.f('store_vectors_pkey'))
    )
    op.create_index(op.f('store_vectors_embedding_idx'), 'store_vectors', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_index(op.f('ix_voice_cache_id'), table_name='voice_cache')
    op.drop_index(op.f('ix_voice_cache_content_hash'), table_name='voice_cache')
    op.drop_table('voice_cache')
    # ### end Alembic commands ###
