"""add auto-increment version to agents table

Revision ID: 0123b2d0bf3c
Revises: 20251114_142810
Create Date: 2025-11-14 08:25:37.958981+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0123b2d0bf3c'
down_revision: Union[str, None] = '20251114_142810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.alter_column('push_notification_history', 'chat_id',
               existing_type=sa.VARCHAR(),
               comment='聊天ID（可选，无聊天推送时为空）',
               existing_nullable=True)
    op.alter_column('push_notification_history', 'stage',
               existing_type=sa.VARCHAR(),
               comment='推送阶段: 10min, 30min, 2h, 24h, 48h',
               existing_comment='推送阶段: 10min, 30min, 2h, no_chat_24h, no_chat_48h 等',
               existing_nullable=False)
    op.drop_index(op.f('ix_push_notification_history_sent_at'), table_name='push_notification_history')
    op.create_index('ix_push_notification_agent_id', 'push_notification_history', ['agent_id'], unique=False)
    op.create_index('ix_push_notification_sent_at', 'push_notification_history', ['sent_at'], unique=False)
    op.create_index('ix_push_notification_user_id', 'push_notification_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_push_notification_user_id', table_name='push_notification_history')
    op.drop_index('ix_push_notification_sent_at', table_name='push_notification_history')
    op.drop_index('ix_push_notification_agent_id', table_name='push_notification_history')
    op.create_index(op.f('ix_push_notification_history_sent_at'), 'push_notification_history', ['sent_at'], unique=False)
    op.alter_column('push_notification_history', 'stage',
               existing_type=sa.VARCHAR(),
               comment='推送阶段: 10min, 30min, 2h, no_chat_24h, no_chat_48h 等',
               existing_comment='推送阶段: 10min, 30min, 2h, 24h, 48h',
               existing_nullable=False)
    op.alter_column('push_notification_history', 'chat_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='聊天ID（可选，无聊天推送时为空）',
               existing_nullable=True)
    op.drop_column('agents', 'version')
    # ### end Alembic commands ###
