"""users add selfie persona summary

Revision ID: cbde9132ac88
Revises: b2d0fb5c7f6f
Create Date: 2026-02-11 08:43:09.334894+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbde9132ac88'
down_revision: Union[str, None] = 'b2d0fb5c7f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('selfie_persona_summary', sa.String(length=1024), nullable=True, comment='根据用户自拍推测的简短画像结论，用于聊天提示词'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'selfie_persona_summary')
    # ### end Alembic commands ###
