"""users add selfie persona summary

Revision ID: de1b8ea1c78b
Revises: 528ca75a97af
Create Date: 2026-02-11 08:39:06.182393+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1b8ea1c78b'
down_revision: Union[str, None] = '528ca75a97af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'selfie_persona_summary',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_comment='根据用户自拍推测的简短画像结论，用于聊天提示词',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'selfie_persona_summary',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               existing_comment='根据用户自拍推测的简短画像结论，用于聊天提示词',
               existing_nullable=True)
    # ### end Alembic commands ###
