"""github-issues

Revision ID: d657261cff67
Revises: a0b3e0778673
Create Date: 2026-02-11 08:11:48.370300+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd657261cff67'
down_revision: Union[str, None] = 'a0b3e0778673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('github_issues', sa.String(length=500), nullable=True, comment='关联的 GitHub issue URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'github_issues')
    # ### end Alembic commands ###
