"""Tests for AgenticLoop chat-only track contracts (envelope / scene / silence).

Generated by Cursor agent for the Stage-1 AgenticLoop convergence review.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from types import SimpleNamespace

from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from app.core.companion_harness.agentic_companion.output_queue import (
    OutputQueue,
)
from app.core.companion_harness.agentic_companion.types import (
    synthetic_user_message_batch,
)
from app.core.companion_harness.companion.dual_llm_chat_branch_envelope import (
    DUAL_LLM_CHAT_RESPONSE_FORMAT,
)
from app.core.companion_harness.companion.langsmith_turn_slice import (
    CompanionTurnLangsmithSlice,
)
from app.core.companion_harness.companion.models import (
    CompanionTurnTrack,
)
from app.core.companion_harness.companion.proactive_chat_envelope import (
    PROACTIVE_CHAT_RESPONSE_FORMAT,
)
from app.core.companion_harness.companion.runtime_channel import (
    ChannelKind,
    TurnRuntimeContext,
)
from app.core.companion_harness.companion.scope import CompanionScope
from app.core.companion_harness.companion.turn_tail_user import (
    TurnTailUserMessage,
)
from app.core.companion_harness.loop.agentic_loop import (
    AgenticLoop,
    _run_chat_only_prompt_plan,
    _UserVisibleOutputAppender,
)
from tests.app.core.companion_harness.loop.context_builder_test_support import (
    loop_execution_for_track,
)
from app.core.companion_harness.loop.context import (
    build_implicit_sign_on_greeting_loop_context,
    build_inner_tick_chat_only_loop_context,
    build_inner_tick_tool_loop_context,
    prompt_plan_from_openai_messages,
)
from app.core.companion_harness.memory.memory_store import MemoryStore
from app.core.companion_harness.memory.memory_store_path_constants import (
    TRANSCRIPT_JSONL_REL,
)
from app.core.llms.client import LLM_SCENE_CHAT, LLM_SCENE_INNER_TICK
from app.core.companion_harness.agentic_companion.types import OutputMessageKind


def _response(content: str) -> SimpleNamespace:
    return SimpleNamespace(
        choices=[
            SimpleNamespace(
                message=SimpleNamespace(content=content, tool_calls=[]),
            )
        ]
    )


def _store() -> MemoryStore:
    store = MemoryStore(
        scope=CompanionScope("user-1", "agent-1", "chat-1"),
        repository=None,
    )
    store.write_document(TRANSCRIPT_JSONL_REL, "")
    return store


def _runtime_context() -> TurnRuntimeContext:
    return TurnRuntimeContext(
        channel=ChannelKind.APP_WS,
        implicit_signal_bundle=None,
    )


def _langsmith_slice() -> CompanionTurnLangsmithSlice:
    return CompanionTurnLangsmithSlice.from_runtime_context(_runtime_context())


def _messages() -> list[dict[str, str]]:
    return [
        {"role": "system", "content": "sys"},
        {"role": "user", "content": "hi"},
    ]


def _appender(store: MemoryStore) -> _UserVisibleOutputAppender:
    queue = MagicMock(spec=OutputQueue)
    queue.append_visible_message = AsyncMock(
        return_value=SimpleNamespace(message_id="out-1")
    )
    return _UserVisibleOutputAppender(
        output_queue=queue,
        batch=synthetic_user_message_batch(
            user_msg_uuid="uid-1",
            track_label="test",
        ),
        store=store,
        image_asset_baseline=0,
    )


def _common_context_kwargs(store: MemoryStore) -> dict:
    _ = store
    return dict(
        messages=_messages(),
        repository_only_store_text=False,
        trace_id="trace-1",
        user_text="hi",
        ts_user=datetime(2026, 1, 1, tzinfo=UTC),
        user_msg_uuid="uid-1",
        transcript_rel=TRANSCRIPT_JSONL_REL,
        langsmith_slice=_langsmith_slice(),
        runtime_context=_runtime_context(),
        stack_depth=1,
        langsmith_trace_id="",
        langsmith_run_id="",
        output_queue=MagicMock(spec=OutputQueue),
        user_message_batch=synthetic_user_message_batch(
            user_msg_uuid="uid-1",
            track_label="test",
        ),
        tail_user_messages=(
            TurnTailUserMessage(
                message_id="uid-1",
                text="hi",
                received_at_utc=datetime(2026, 1, 1, tzinfo=UTC),
            ),
        ),
        prompt_plan=prompt_plan_from_openai_messages(_messages(), tools=()),
    )


@pytest.mark.asyncio
async def test_greeting_uses_dual_llm_envelope_with_retrial() -> None:
    store = _store()
    context = build_implicit_sign_on_greeting_loop_context(
        **_common_context_kwargs(store),
        execution=loop_execution_for_track(
            track=CompanionTurnTrack.IMPLICIT_SIGN_ON_GREETING,
            user_text="hi",
            has_openai_tools=False,
        ),
    )
    envelope = json.dumps(
        {
            "user_facing_reply": "Welcome back!",
            "importance_round": 3,
            "importance_user_message": 2,
            "importance_assistant_message": 3,
            "output_to_user": True,
            "turn_recall": "greeted after sign-on",
        }
    )
    llm_client = MagicMock()
    llm_client.resolve_model.return_value = SimpleNamespace(
        id_on_provider="test/model"
    )
    llm_client.chat_completion_with_retrial = AsyncMock(
        return_value=_response(envelope)
    )
    appender = _appender(store)

    result = await _run_chat_only_prompt_plan(
        context,
        llm_client=llm_client,
        appender=appender,
    )

    call = llm_client.chat_completion_with_retrial.await_args
    assert call.kwargs["response_format"] == DUAL_LLM_CHAT_RESPONSE_FORMAT
    assert call.kwargs["scene"] == LLM_SCENE_CHAT
    assert result.assistant_text == "Welcome back!"
    assert result.significance_meta is not None
    assert result.turn_recall == "greeted after sign-on"
    appender.output_queue.append_visible_message.assert_not_awaited()


@pytest.mark.asyncio
async def test_scheduled_uses_proactive_envelope_and_inner_tick_scene() -> None:
    store = _store()
    context = build_inner_tick_chat_only_loop_context(
        track=CompanionTurnTrack.INNER_TICK_SCHEDULED,
        **_common_context_kwargs(store),
        execution=loop_execution_for_track(
            track=CompanionTurnTrack.INNER_TICK_SCHEDULED,
            user_text="hi",
            has_openai_tools=False,
        ),
    )
    envelope = json.dumps(
        {"output_to_user": True, "message": "Reminder: stretch break."}
    )
    llm_client = MagicMock()
    llm_client.resolve_model.return_value = SimpleNamespace(
        id_on_provider="test/model"
    )
    llm_client.chat_completion = AsyncMock(return_value=_response(envelope))
    appender = _appender(store)

    result = await _run_chat_only_prompt_plan(
        context,
        llm_client=llm_client,
        appender=appender,
    )

    call = llm_client.chat_completion.await_args
    assert call.kwargs["response_format"] == PROACTIVE_CHAT_RESPONSE_FORMAT
    assert call.kwargs["scene"] == LLM_SCENE_INNER_TICK
    assert call.kwargs["high_reasoning"] is False
    assert result.assistant_text == "Reminder: stretch break."
    append_call = appender.output_queue.append_visible_message.await_args
    assert append_call.args[0].kind == OutputMessageKind.SCHEDULED


@pytest.mark.asyncio
async def test_scheduled_envelope_silence_skips_output_and_row() -> None:
    store = _store()
    context = build_inner_tick_chat_only_loop_context(
        track=CompanionTurnTrack.INNER_TICK_SCHEDULED,
        **_common_context_kwargs(store),
        execution=loop_execution_for_track(
            track=CompanionTurnTrack.INNER_TICK_SCHEDULED,
            user_text="hi",
            has_openai_tools=False,
        ),
    )
    envelope = json.dumps({"output_to_user": False, "message": ""})
    llm_client = MagicMock()
    llm_client.resolve_model.return_value = SimpleNamespace(
        id_on_provider="test/model"
    )
    llm_client.chat_completion = AsyncMock(return_value=_response(envelope))
    appender = _appender(store)

    result = await _run_chat_only_prompt_plan(
        context,
        llm_client=llm_client,
        appender=appender,
    )

    assert result.assistant_text == ""
    assert result.skip_final_transcript_assistant_row is True
    appender.output_queue.append_visible_message.assert_not_awaited()


@pytest.mark.asyncio
async def test_proactive_uses_chat_scene_and_high_reasoning() -> None:
    store = _store()
    context = build_inner_tick_chat_only_loop_context(
        track=CompanionTurnTrack.INNER_TICK_PROACTIVE_CHAT,
        **_common_context_kwargs(store),
        execution=loop_execution_for_track(
            track=CompanionTurnTrack.INNER_TICK_PROACTIVE_CHAT,
            user_text="hi",
            has_openai_tools=False,
        ),
    )
    envelope = json.dumps(
        {"output_to_user": True, "message": "Thinking of you."}
    )
    llm_client = MagicMock()
    llm_client.resolve_model.return_value = SimpleNamespace(
        id_on_provider="test/model"
    )
    llm_client.chat_completion = AsyncMock(return_value=_response(envelope))
    appender = _appender(store)

    result = await _run_chat_only_prompt_plan(
        context,
        llm_client=llm_client,
        appender=appender,
    )

    call = llm_client.chat_completion.await_args
    assert call.kwargs["response_format"] == PROACTIVE_CHAT_RESPONSE_FORMAT
    assert call.kwargs["scene"] == LLM_SCENE_CHAT
    assert call.kwargs["high_reasoning"] is True
    assert result.assistant_text == "Thinking of you."
    append_call = appender.output_queue.append_visible_message.await_args
    assert append_call.args[0].kind == OutputMessageKind.PROACTIVE


@pytest.mark.asyncio
async def test_autonomy_tool_loop_never_appends_visible_output() -> None:
    store = _store()
    queue = MagicMock(spec=OutputQueue)
    queue.append_visible_message = AsyncMock()
    kwargs = _common_context_kwargs(store)
    kwargs["output_queue"] = queue
    tools = [{"type": "function", "function": {"name": "noop"}}]
    kwargs["prompt_plan"] = prompt_plan_from_openai_messages(
        _messages(), tools=tuple(tools)
    )
    context = build_inner_tick_tool_loop_context(
        track=CompanionTurnTrack.INNER_TICK_AUTONOMY,
        tools_for_turn=tools,
        **kwargs,
        execution=loop_execution_for_track(
            track=CompanionTurnTrack.INNER_TICK_AUTONOMY,
            user_text="hi",
            has_openai_tools=True,
        ),
    )

    captured_sinks: list[object] = []

    async def _fake_prompt_plan_loop(  # type: ignore[no-untyped-def]
        ctx,
        *,
        store,
        llm_client,
        interim_output_sink,
        max_tool_call_rounds,
    ):
        captured_sinks.append(interim_output_sink)
        from app.core.companion_harness.companion.in_turn_sync_tool_loop import (
            InTurnSyncToolLoopResult,
        )

        return InTurnSyncToolLoopResult(
            assistant_text="private musing",
            langsmith_trace_id="",
            langsmith_run_id="",
            skip_final_transcript_assistant_row=False,
            last_interim_assistant_msg_uuid=None,
            loop_persisted_user_transcript=True,
        )

    with patch(
        "app.core.companion_harness.loop.agentic_loop._run_prompt_plan_tool_loop",
        new=AsyncMock(side_effect=_fake_prompt_plan_loop),
    ):
        result = await AgenticLoop(
            store=store,
            llm_client=MagicMock(),
            legacy_llm_client=MagicMock(),
        ).run_single_llm_turn(context=context)

    assert captured_sinks == [None]
    queue.append_visible_message.assert_not_awaited()
    assert result.output_message_ids == ()
