"""Users 表中增加 password 字段

Revision ID: 1055e2288eca
Revises: 338a576cd178
Create Date: 2025-11-27 19:26:29.652542+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1055e2288eca"
down_revision: Union[str, None] = "338a576cd178"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 EMAIL 到 authtype 枚举类型
    # 注意：PostgreSQL 不支持 IF NOT EXISTS，如果值已存在会报错，但可以安全忽略
    # 本 revision 被 downgrade 后，EMAIL 枚举值不会被删除，因为 downgrade 不会执行到这个语句。
    # 因此只能手动处理。
    op.execute("ALTER TYPE authtype ADD VALUE 'EMAIL'")
    # 添加 password 字段到 users 表
    op.add_column(
        "users",
        sa.Column(
            "password", sa.String(), nullable=True, comment="密码哈希，用于 email 登录"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除 password 字段
    op.drop_column("users", "password")

    # 注意：PostgreSQL 不支持直接删除枚举值（ALTER TYPE ... DROP VALUE）
    # 如果需要删除 EMAIL 枚举值，需要执行以下步骤：
    # 1. 删除所有使用 EMAIL auth_type 的用户记录（或更新为其他类型）
    # 2. 创建临时枚举类型（不包含 EMAIL）
    # 3. 更新 users 表的 auth_type 列类型
    # 4. 删除旧枚举类型
    # 5. 重命名新枚举类型
    #
    # 由于这是新功能，如果还没有生产数据使用 EMAIL，可以保留枚举值
    # 如果需要完整回退，可以参考 20250703_130000_add_quarterly_subscription_type.py 的实现
    #
    # 示例完整回退代码（仅在确实需要删除枚举值时使用）：
    # op.execute("DELETE FROM users WHERE auth_type = 'EMAIL'")
    # op.execute("CREATE TYPE authtype_temp AS ENUM ('PHONE', 'GOOGLE', 'GUEST')")
    # op.execute("ALTER TABLE users ALTER COLUMN auth_type TYPE authtype_temp USING auth_type::text::authtype_temp")
    # op.execute("DROP TYPE authtype")
    # op.execute("ALTER TYPE authtype_temp RENAME TO authtype")
    # ### end Alembic commands ###
