"""添加 points（积分）列到 agents 表

Revision ID: 2c1d10b2202b
Revises: 20251202_141507
Create Date: 2025-12-06 05:05:56.278515+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c1d10b2202b"
down_revision: Union[str, None] = "20251202_141507"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除 report_reason 表（如果存在）
    # 该表已被废弃，举报原因现在使用硬编码（见 app/models/report.py）
    conn = op.get_bind()
    conn.execute(sa.text("DROP TABLE IF EXISTS report_reason"))
    op.add_column(
        "agents",
        sa.Column(
            "points",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=True,
            comment="角色积分，用于角色热度排名（boosting feature）",
        ),
    )
    op.alter_column(
        "character_theme_agents",
        "theme_id",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="专区ID",
        existing_nullable=False,
    )
    op.alter_column(
        "character_theme_agents",
        "agent_id",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="角色ID",
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_character_theme_agents_order_index"),
        table_name="character_theme_agents",
    )
    op.drop_index(
        op.f("ix_character_theme_agents_theme_id"),
        table_name="character_theme_agents",
    )
    op.alter_column(
        "character_themes",
        "id",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="专区ID",
        existing_nullable=False,
    )
    op.alter_column(
        "character_themes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "character_themes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "character_themes",
        "id",
        existing_type=sa.VARCHAR(),
        comment="专区ID",
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_character_theme_agents_theme_id"),
        "character_theme_agents",
        ["theme_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_character_theme_agents_order_index"),
        "character_theme_agents",
        ["order_index"],
        unique=False,
    )
    op.alter_column(
        "character_theme_agents",
        "agent_id",
        existing_type=sa.VARCHAR(),
        comment="角色ID",
        existing_nullable=False,
    )
    op.alter_column(
        "character_theme_agents",
        "theme_id",
        existing_type=sa.VARCHAR(),
        comment="专区ID",
        existing_nullable=False,
    )
    op.drop_column("agents", "points")
    op.create_table(
        "report_reason",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "code",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
            comment="举报原因代码",
        ),
        sa.Column(
            "description",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="举报原因描述",
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
            comment="是否启用",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
            comment="更新时间",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("report_reason_pkey")),
        sa.UniqueConstraint(
            "code",
            name=op.f("report_reason_code_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
