"""creator_id nullable=false

Revision ID: 355ceb5017ff
Revises: 62b632b916ef
Create Date: 2025-09-27 03:45:07.016633+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '355ceb5017ff'
down_revision: Union[str, None] = '62b632b916ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 如果 creator_id 为空，则设置为默认创建者ID
    # 这个 User ID 是共用的默认管理员用户 ID，后端系统部署时必须，使用 tools/scripts/init_admin_user.py 写入数据库。
    # 手动添加
    op.execute("UPDATE agents SET creator_id = 'user-01JWZ34Y4D1C92GD86A5R6EWYJ' WHERE creator_id IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'creator_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'creator_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
