"""remove readable_id constraints

Revision ID: 4a90b1f01430
Revises: 20250130_120000
Create Date: 2025-11-13 06:53:47.607852+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a90b1f01430'
down_revision: Union[str, None] = '20250130_120000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'readable_id',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.drop_index(op.f('ix_agents_readable_id'), table_name='agents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agents_readable_id'), 'agents', ['readable_id'], unique=True)
    op.alter_column('agents', 'readable_id',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###
