"""system settings and voice cache tables

Revision ID: 43b18ddc9846
Revises: 20250726_001000
Create Date: 2025-08-05 04:16:13.353377+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43b18ddc9846'
down_revision: Union[str, None] = '20250726_001000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键名'),
    sa.Column('value', sa.Text(), nullable=False, comment='配置值'),
    sa.Column('value_type', sa.Enum('STRING', 'INTEGER', 'FLOAT', 'BOOLEAN', 'JSON', name='settingtype'), nullable=False, comment='值类型'),
    sa.Column('category', sa.Enum('SUBSCRIPTION_LIMITS', 'SYSTEM_FEATURES', 'SECURITY', 'GENERAL', name='settingcategory'), nullable=False, comment='配置分类'),
    sa.Column('description', sa.Text(), nullable=True, comment='配置描述'),
    sa.Column('default_value', sa.Text(), nullable=True, comment='默认值'),
    sa.Column('is_system', sa.Boolean(), nullable=True, comment='是否为系统内置配置'),
    sa.Column('is_readonly', sa.Boolean(), nullable=True, comment='是否只读'),
    sa.Column('updated_by', sa.String(), nullable=True, comment='最后更新者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_system_settings_category', 'system_settings', ['category'], unique=False)
    op.create_index('ix_system_settings_updated_at', 'system_settings', ['updated_at'], unique=False)
    op.create_table('verification_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_id'), 'verification_codes', ['id'], unique=False)
    op.create_index(op.f('ix_verification_codes_phone'), 'verification_codes', ['phone'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', 'VOICE', 'VIDEO', name='resourcetype'), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('resource_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.drop_column('agent_followers', 'created_at')
    op.drop_constraint(op.f('uq_agents_readable_id'), 'agents', type_='unique')
    op.drop_index(op.f('ix_agents_readable_id'), table_name='agents')
    op.create_index(op.f('ix_agents_readable_id'), 'agents', ['readable_id'], unique=True)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    # 注释：保留唯一约束，同时添加普通索引以优化查询性能
    # 原来的代码错误地删除了唯一约束，这里修复为保留唯一约束
    # op.drop_index(op.f('uq_chats_user_agent_active'), table_name='chats', postgresql_where='(is_active = true)')
    op.create_index('ix_chats_user_agent_active', 'chats', ['user_id', 'agent_id', 'is_active'], unique=False)
    op.alter_column('device_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('device_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index('ix_device_tokens_token', 'device_tokens', ['token'], unique=True)
    op.alter_column('evaluation_interactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('evaluation_results', sa.Column('agent_name', sa.String(length=255), nullable=True, comment='智能体名称（冗余字段，提高查询效率）'))
    op.alter_column('evaluation_results', 'is_success',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否成功完成',
               existing_server_default=sa.text('true'))
    op.alter_column('evaluation_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('evaluation_sessions', 'id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='评测会话ID',
               existing_nullable=False)
    op.alter_column('evaluation_sessions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='evaluation_status'),
               nullable=True,
               existing_comment='评测状态',
               existing_server_default=sa.text("'PENDING'::evaluation_status"))
    op.alter_column('evaluation_sessions', 'use_new_user_identity',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否使用新用户身份',
               existing_server_default=sa.text('false'))
    op.alter_column('evaluation_sessions', 'total_tests',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='总测试数量',
               existing_server_default=sa.text('0'))
    op.alter_column('evaluation_sessions', 'completed_tests',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='已完成测试数量',
               existing_server_default=sa.text('0'))
    op.alter_column('evaluation_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('evaluation_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='使用次数',
               existing_server_default=sa.text('0'))
    op.alter_column('evaluation_templates', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否公开',
               existing_server_default=sa.text('false'))
    op.alter_column('evaluation_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否活跃',
               existing_server_default=sa.text('true'))
    op.alter_column('evaluation_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('report', 'id',
               existing_type=sa.VARCHAR(length=100),
               comment='举报记录ID',
               existing_nullable=False)
    op.alter_column('report', 'target_id',
               existing_type=sa.VARCHAR(length=100),
               comment='被举报对象ID',
               existing_nullable=False)
    op.alter_column('report', 'target_type',
               existing_type=sa.VARCHAR(length=50),
               comment='被举报对象类型',
               existing_nullable=False)
    op.alter_column('report', 'reporter_id',
               existing_type=sa.VARCHAR(length=100),
               comment='举报人ID',
               existing_nullable=False)
    op.alter_column('report', 'reason_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment='举报原因ID列表',
               existing_nullable=False)
    op.alter_column('report', 'image_urls',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='举报图片URL列表',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('report', 'description',
               existing_type=sa.TEXT(),
               comment='举报描述',
               existing_nullable=True)
    op.alter_column('report', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_report_created_at'), table_name='report')
    op.drop_index(op.f('ix_report_reporter_id'), table_name='report')
    op.drop_index(op.f('ix_report_target_id'), table_name='report')
    op.alter_column('report_reason', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='举报原因代码',
               existing_nullable=False)
    op.alter_column('report_reason', 'description',
               existing_type=sa.TEXT(),
               comment='举报原因描述',
               existing_nullable=True)
    op.alter_column('report_reason', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='是否启用',
               existing_server_default=sa.text('true'))
    op.alter_column('report_reason', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('report_reason', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
    op.drop_index(op.f('ix_report_reason_code'), table_name='report_reason')
    op.alter_column('settings', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('settings', 'voice_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('settings', 'keep_talking',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('settings', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('subscription_plans', sa.Column('background_generation_limit_per_day', sa.Integer(), nullable=True, comment='每日背景图生成次数限制，-1为无限制'))
    op.drop_table_comment(
        'subscription_plans',
        existing_comment='订阅计划表',
        schema=None
    )
    op.drop_table_comment(
        'subscription_transactions',
        existing_comment='订阅交易记录表',
        schema=None
    )
    op.drop_table_comment(
        'subscription_usage',
        existing_comment='订阅使用记录表',
        schema=None
    )
    op.alter_column('user_deletion_logs', 'original_user_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='原始用户数据快照',
               existing_nullable=True)
    op.drop_table_comment(
        'user_deletion_logs',
        existing_comment='用户删除审计日志表',
        schema=None
    )
    op.alter_column('user_notifications', 'dynamic_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('user_notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('user_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_notifications', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_table_comment(
        'user_subscriptions',
        existing_comment='用户订阅记录表',
        schema=None
    )
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(),
               comment='用户唯一标识符',
               existing_nullable=False)
    op.alter_column('users', 'readable_id',
               existing_type=sa.VARCHAR(length=8),
               comment='用户可读ID',
               existing_nullable=False)
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(),
               comment='用户昵称，可搜索',
               existing_nullable=True)
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(),
               comment='用户头像URL',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment='邮箱地址，唯一，用于登录',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               comment='手机号码，唯一，用于登录',
               existing_nullable=True)
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='gender'),
               comment='性别：男/女/其他',
               existing_nullable=True)
    op.alter_column('users', 'age_group',
               existing_type=sa.VARCHAR(),
               comment='年龄段',
               existing_nullable=True)
    op.alter_column('users', 'description',
               existing_type=sa.VARCHAR(),
               comment='个人简介',
               existing_nullable=True)
    op.alter_column('users', 'auth_type',
               existing_type=postgresql.ENUM('PHONE', 'GOOGLE', 'GUEST', name='authtype'),
               comment='认证类型：手机号/Google/游客',
               existing_nullable=False)
    op.alter_column('users', 'google_id',
               existing_type=sa.VARCHAR(),
               comment='Google账号ID，唯一，用于Google登录',
               existing_nullable=True)
    op.alter_column('users', 'device_id',
               existing_type=sa.VARCHAR(),
               comment='设备ID，唯一，用于设备识别',
               existing_nullable=True)
    op.alter_column('users', 'system_language',
               existing_type=sa.VARCHAR(),
               comment='系统语言偏好，默认英语',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='账号是否激活',
               existing_nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='是否为超级管理员',
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_anonymized_at'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_constraint(op.f('uq_users_readable_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_readable_id'), table_name='users')
    op.create_index(op.f('ix_users_readable_id'), 'users', ['readable_id'], unique=True)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['device_id'])
    op.create_unique_constraint(None, 'users', ['phone'])
    op.create_unique_constraint(None, 'users', ['google_id'])
    op.alter_column('voice_cache', 'content_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('voice_cache_content_hash_key'), 'voice_cache', type_='unique')
    op.drop_index(op.f('ix_voice_cache_content_hash'), table_name='voice_cache')
    op.create_index(op.f('ix_voice_cache_content_hash'), 'voice_cache', ['content_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_cache_content_hash'), table_name='voice_cache')
    op.create_index(op.f('ix_voice_cache_content_hash'), 'voice_cache', ['content_hash'], unique=False)
    op.create_unique_constraint(op.f('voice_cache_content_hash_key'), 'voice_cache', ['content_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('voice_cache', 'content_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_readable_id'), table_name='users')
    op.create_index(op.f('ix_users_readable_id'), 'users', ['readable_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_readable_id'), 'users', ['readable_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_anonymized_at'), 'users', ['anonymized_at'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='是否为超级管理员',
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='账号是否激活',
               existing_nullable=True)
    op.alter_column('users', 'system_language',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='系统语言偏好，默认英语',
               existing_nullable=True)
    op.alter_column('users', 'device_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='设备ID，唯一，用于设备识别',
               existing_nullable=True)
    op.alter_column('users', 'google_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Google账号ID，唯一，用于Google登录',
               existing_nullable=True)
    op.alter_column('users', 'auth_type',
               existing_type=postgresql.ENUM('PHONE', 'GOOGLE', 'GUEST', name='authtype'),
               comment=None,
               existing_comment='认证类型：手机号/Google/游客',
               existing_nullable=False)
    op.alter_column('users', 'description',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='个人简介',
               existing_nullable=True)
    op.alter_column('users', 'age_group',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='年龄段',
               existing_nullable=True)
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='gender'),
               comment=None,
               existing_comment='性别：男/女/其他',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='手机号码，唯一，用于登录',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='邮箱地址，唯一，用于登录',
               existing_nullable=True)
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='用户头像URL',
               existing_nullable=True)
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='用户昵称，可搜索',
               existing_nullable=True)
    op.alter_column('users', 'readable_id',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='用户可读ID',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='用户唯一标识符',
               existing_nullable=False)
    op.create_table_comment(
        'user_subscriptions',
        '用户订阅记录表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user_notifications', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('user_notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_notifications', 'read_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('user_notifications', 'dynamic_params',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table_comment(
        'user_deletion_logs',
        '用户删除审计日志表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user_deletion_logs', 'original_user_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='原始用户数据快照',
               existing_nullable=True)
    op.create_table_comment(
        'subscription_usage',
        '订阅使用记录表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'subscription_transactions',
        '订阅交易记录表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'subscription_plans',
        '订阅计划表',
        existing_comment=None,
        schema=None
    )
    op.drop_column('subscription_plans', 'background_generation_limit_per_day')
    op.alter_column('settings', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('settings', 'keep_talking',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('settings', 'voice_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('settings', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.create_index(op.f('ix_report_reason_code'), 'report_reason', ['code'], unique=True)
    op.alter_column('report_reason', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('report_reason', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('report_reason', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='是否启用',
               existing_server_default=sa.text('true'))
    op.alter_column('report_reason', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='举报原因描述',
               existing_nullable=True)
    op.alter_column('report_reason', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='举报原因代码',
               existing_nullable=False)
    op.create_index(op.f('ix_report_target_id'), 'report', ['target_id'], unique=False)
    op.create_index(op.f('ix_report_reporter_id'), 'report', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_report_created_at'), 'report', ['created_at'], unique=False)
    op.alter_column('report', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('report', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='举报描述',
               existing_nullable=True)
    op.alter_column('report', 'image_urls',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='举报图片URL列表',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('report', 'reason_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment=None,
               existing_comment='举报原因ID列表',
               existing_nullable=False)
    op.alter_column('report', 'reporter_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='举报人ID',
               existing_nullable=False)
    op.alter_column('report', 'target_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='被举报对象类型',
               existing_nullable=False)
    op.alter_column('report', 'target_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='被举报对象ID',
               existing_nullable=False)
    op.alter_column('report', 'id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='举报记录ID',
               existing_nullable=False)
    op.alter_column('notification_templates', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_templates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('evaluation_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('evaluation_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否活跃',
               existing_server_default=sa.text('true'))
    op.alter_column('evaluation_templates', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否公开',
               existing_server_default=sa.text('false'))
    op.alter_column('evaluation_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='使用次数',
               existing_server_default=sa.text('0'))
    op.alter_column('evaluation_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('evaluation_sessions', 'completed_tests',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='已完成测试数量',
               existing_server_default=sa.text('0'))
    op.alter_column('evaluation_sessions', 'total_tests',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='总测试数量',
               existing_server_default=sa.text('0'))
    op.alter_column('evaluation_sessions', 'use_new_user_identity',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否使用新用户身份',
               existing_server_default=sa.text('false'))
    op.alter_column('evaluation_sessions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='evaluation_status'),
               nullable=False,
               existing_comment='评测状态',
               existing_server_default=sa.text("'PENDING'::evaluation_status"))
    op.alter_column('evaluation_sessions', 'id',
               existing_type=sa.VARCHAR(),
               comment='评测会话ID',
               existing_nullable=False)
    op.alter_column('evaluation_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('evaluation_results', 'is_success',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否成功完成',
               existing_server_default=sa.text('true'))
    op.drop_column('evaluation_results', 'agent_name')
    op.alter_column('evaluation_interactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_device_tokens_token', table_name='device_tokens')
    op.alter_column('device_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('device_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # 修复：只删除普通索引，保留唯一约束
    op.drop_index('ix_chats_user_agent_active', table_name='chats')
    # op.create_index(op.f('uq_chats_user_agent_active'), 'chats', ['user_id', 'agent_id'], unique=True, postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_readable_id'), table_name='agents')
    op.create_index(op.f('ix_agents_readable_id'), 'agents', ['readable_id'], unique=False)
    op.create_unique_constraint(op.f('uq_agents_readable_id'), 'agents', ['readable_id'], postgresql_nulls_not_distinct=False)
    op.add_column('agent_followers', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_verification_codes_phone'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_id'), table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_index('ix_system_settings_updated_at', table_name='system_settings')
    op.drop_index('ix_system_settings_category', table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
