"""create all tables

Revision ID: 109ce7b3713c
Revises: 1c845f00fc71
Create Date: 2025-05-28 09:45:10.460352+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "109ce7b3713c"
down_revision: Union[str, None] = "1c845f00fc71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先删除所有表
    op.execute("DROP TABLE IF EXISTS settings CASCADE")
    op.execute("DROP TABLE IF EXISTS agent_followers CASCADE")
    op.execute("DROP TABLE IF EXISTS messages CASCADE")
    op.execute("DROP TABLE IF EXISTS chat_settings CASCADE")
    op.execute("DROP TABLE IF EXISTS agents CASCADE")
    op.execute("DROP TABLE IF EXISTS users CASCADE")

    # 删除已存在的枚举类型
    op.execute("DROP TYPE IF EXISTS gender CASCADE")
    op.execute("DROP TYPE IF EXISTS authtype CASCADE")
    op.execute("DROP TYPE IF EXISTS visibility CASCADE")
    op.execute("DROP TYPE IF EXISTS agentstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS messagetype CASCADE")
    op.execute("DROP TYPE IF EXISTS sendertype CASCADE")

    # 创建枚举类型
    gender = postgresql.ENUM(
        "MALE", "FEMALE", "OTHER", name="gender", create_type=False
    )
    authtype = postgresql.ENUM(
        "PHONE", "GOOGLE", "GUEST", name="authtype", create_type=False
    )
    visibility = postgresql.ENUM(
        "PUBLIC", "PRIVATE", name="visibility", create_type=False
    )
    agentstatus = postgresql.ENUM(
        "PENDING", "APPROVED", "REJECTED", name="agentstatus", create_type=False
    )
    messagetype = postgresql.ENUM(
        "TEXT", "VOICE", "IMAGE", name="messagetype", create_type=False
    )
    sendertype = postgresql.ENUM("USER", "AI", name="sendertype", create_type=False)

    # 创建枚举类型
    gender.create(op.get_bind(), checkfirst=True)
    authtype.create(op.get_bind(), checkfirst=True)
    visibility.create(op.get_bind(), checkfirst=True)
    agentstatus.create(op.get_bind(), checkfirst=True)
    messagetype.create(op.get_bind(), checkfirst=True)
    sendertype.create(op.get_bind(), checkfirst=True)

    # 创建 users 表
    op.create_table(
        "users",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("nickname", sa.VARCHAR(), nullable=True),
        sa.Column("avatar", sa.VARCHAR(), nullable=True),
        sa.Column("email", sa.VARCHAR(), nullable=True),
        sa.Column("phone", sa.VARCHAR(), nullable=True),
        sa.Column("gender", gender, nullable=True),
        sa.Column("age_group", sa.VARCHAR(), nullable=True),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("auth_type", authtype, nullable=False),
        sa.Column("system_language", sa.VARCHAR(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("device_id", sa.VARCHAR(), nullable=True),
        sa.Column("google_id", sa.VARCHAR(), nullable=True),
        sa.Column(
            "is_superuser",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_device_id", "users", ["device_id"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.create_index("ix_users_google_id", "users", ["google_id"], unique=False)
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.create_index("ix_users_phone", "users", ["phone"], unique=False)

    # 创建 agents 表
    op.create_table(
        "agents",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=30), nullable=False),
        sa.Column("gender", gender, nullable=False),
        sa.Column("avatar", sa.VARCHAR(), nullable=True),
        sa.Column("voice_id", sa.VARCHAR(), nullable=True),
        sa.Column("settings", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("intro", sa.VARCHAR(), nullable=True),
        sa.Column("opening", sa.VARCHAR(), nullable=True),
        sa.Column("visibility", visibility, nullable=True),
        sa.Column("photos", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("category", sa.VARCHAR(), nullable=True),
        sa.Column("status", agentstatus, nullable=True),
        sa.Column("creator_id", sa.VARCHAR(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agents_id", "agents", ["id"], unique=False)

    # 创建 messages 表
    op.create_table(
        "messages",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("content", sa.VARCHAR(), nullable=True),
        sa.Column("type", messagetype, nullable=True),
        sa.Column("sender_type", sendertype, nullable=True),
        sa.Column("sender_id", sa.VARCHAR(), nullable=True),
        sa.Column("agent_id", sa.VARCHAR(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_messages_id", "messages", ["id"], unique=False)

    # 创建 chat_settings 表
    op.create_table(
        "chat_settings",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("user_id", sa.VARCHAR(), nullable=True),
        sa.Column("agent_id", sa.VARCHAR(), nullable=True),
        sa.Column("language", sa.VARCHAR(), nullable=True),
        sa.Column("voice_enabled", sa.BOOLEAN(), nullable=True),
        sa.Column("keep_talking", sa.BOOLEAN(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_chat_settings_id", "chat_settings", ["id"], unique=False)

    # 创建 agent_followers 表
    op.create_table(
        "agent_followers",
        sa.Column("agent_id", sa.VARCHAR(), nullable=False),
        sa.Column("user_id", sa.VARCHAR(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("agent_id", "user_id"),
    )

    # 创建 settings 表
    op.create_table(
        "settings",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("user_id", sa.VARCHAR(), nullable=False),
        sa.Column(
            "language",
            sa.VARCHAR(),
            server_default=sa.text("'en'::character varying"),
            nullable=False,
        ),
        sa.Column(
            "voice_enabled",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "keep_talking", sa.BOOLEAN(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index("ix_settings_id", "settings", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先删除所有表
    op.execute("DROP TABLE IF EXISTS settings CASCADE")
    op.execute("DROP TABLE IF EXISTS agent_followers CASCADE")
    op.execute("DROP TABLE IF EXISTS messages CASCADE")
    op.execute("DROP TABLE IF EXISTS chat_settings CASCADE")
    op.execute("DROP TABLE IF EXISTS agents CASCADE")
    op.execute("DROP TABLE IF EXISTS users CASCADE")

    # 删除枚举类型
    op.execute("DROP TYPE IF EXISTS gender CASCADE")
    op.execute("DROP TYPE IF EXISTS authtype CASCADE")
    op.execute("DROP TYPE IF EXISTS visibility CASCADE")
    op.execute("DROP TYPE IF EXISTS agentstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS messagetype CASCADE")
    op.execute("DROP TYPE IF EXISTS sendertype CASCADE")
    # ### end Alembic commands ###
