"""report 数据表中增加 reason_codes 字段，并修改 reason_ids 为可空

Revision ID: 893af85e4092
Revises: 6a8ac9b77c0c
Create Date: 2025-11-29 23:37:28.266091+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "893af85e4092"
down_revision: Union[str, None] = "6a8ac9b77c0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "report",
        sa.Column(
            "reason_codes",
            sa.ARRAY(sa.String()),
            nullable=True,
            comment="举报原因代码列表，用来替代 reason_ids，因为 id 很难维护",
        ),
    )
    op.alter_column(
        "report",
        "reason_ids",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        nullable=True,
        comment="[DEPRECATED] 举报原因ID列表，使用 reason_codes 代替",
        existing_comment="举报原因ID列表",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "report",
        "reason_ids",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        nullable=False,
        comment="举报原因ID列表",
        existing_comment="[DEPRECATED] 举报原因ID列表，使用 reason_codes 代替",
    )
    op.drop_column("report", "reason_codes")
    # ### end Alembic commands ###
