"""add_opening_audio_url_to_agents

Revision ID: ab7f71ad458d
Revises: 75796d073cb2
Create Date: 2025-09-09 07:15:51.549799+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7f71ad458d'
down_revision: Union[str, None] = '75796d073cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if opening_audio_url column already exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('agents')]
    
    if 'opening_audio_url' not in columns:
        op.add_column('agents', sa.Column('opening_audio_url', sa.String(), nullable=True))
        print("Added opening_audio_url column to agents table")
    else:
        print("opening_audio_url column already exists in agents table, skipping")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if opening_audio_url column exists before dropping
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('agents')]
    
    if 'opening_audio_url' in columns:
        op.drop_column('agents', 'opening_audio_url')
        print("Dropped opening_audio_url column from agents table")
    else:
        print("opening_audio_url column does not exist in agents table, skipping")
    
    # ### end Alembic commands ###
