"""add report tables

Revision ID: a893fe42f1cf
Revises: 109ce7b3713c
Create Date: 2025-06-05 07:49:03.000000+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a893fe42f1cf"
down_revision: Union[str, None] = "add_prompt_to_agents"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 创建 report_reason 表
    op.create_table(
        "report_reason",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )

    # 创建 report 表
    op.create_table(
        "report",
        sa.Column("id", sa.String(100), nullable=False),
        sa.Column("target_id", sa.String(100), nullable=False),
        sa.Column("target_type", sa.String(50), nullable=False),
        sa.Column("reporter_id", sa.String(100), nullable=False),
        sa.Column("reason_ids", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column(
            "image_urls",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=True,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # 创建索引
    op.create_index("ix_report_reason_code", "report_reason", ["code"], unique=True)
    op.create_index("ix_report_target_id", "report", ["target_id"], unique=False)
    op.create_index("ix_report_reporter_id", "report", ["reporter_id"], unique=False)
    op.create_index("ix_report_created_at", "report", ["created_at"])
    # 添加联合索引
    op.create_index(
        "ix_report_target_reporter", "report", ["target_id", "reporter_id"], unique=True
    )

    # 添加一些默认的举报原因
    op.execute("""
        INSERT INTO report_reason (code, description) VALUES
        ('SENSITIVE_OR_SEXUAL_CONTENT', 'Sensitive or sexual content'),
        ('MISINFORMATION', 'Misinformation'),
        ('FRAUD_OR_SCAMS', 'Fraud or scams'),
        ('VIOLATION_OF_PRIVACY', 'Violation of privacy'),
        ('HARMFUL_TO_MINORS', 'Harmful to minors'),
        ('VIOLATION_OF_INTELLECTUAL_PROPERTY', 'Violations of my intellectual property')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_report_created_at", table_name="report")
    op.drop_index("ix_report_reporter_id", table_name="report")
    op.drop_index("ix_report_target_id", table_name="report")
    op.drop_index("ix_report_target_reporter", table_name="report")
    op.drop_index("ix_report_reason_code", table_name="report_reason")
    op.drop_table("report")
    op.drop_table("report_reason")
    # ### end Alembic commands ###
