"""users.readable_id 删除 unique nullable=false index

Revision ID: ac1a943ddb73
Revises: 893af85e4092
Create Date: 2025-11-30 20:42:29.688404+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ac1a943ddb73"
down_revision: Union[str, None] = "893af85e4092"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("report_reason")
    op.alter_column(
        "users",
        "readable_id",
        existing_type=sa.VARCHAR(length=8),
        nullable=True,
        comment="【已废弃】用户可读ID",
        existing_comment="用户可读ID",
    )
    op.drop_index(op.f("ix_users_readable_id"), table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_users_readable_id"), "users", ["readable_id"], unique=True
    )
    op.alter_column(
        "users",
        "readable_id",
        existing_type=sa.VARCHAR(length=8),
        nullable=False,
        comment="用户可读ID",
        existing_comment="【已废弃】用户可读ID",
    )
    op.create_table(
        "report_reason",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "code",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
            comment="举报原因代码",
        ),
        sa.Column(
            "description",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="举报原因描述",
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
            comment="是否启用",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
            comment="更新时间",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("report_reason_pkey")),
        sa.UniqueConstraint(
            "code",
            name=op.f("report_reason_code_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
