"""make_creator_id_nullable

Revision ID: 959ca996a9d7
Revises: add_prompt_to_agents
Create Date: 2025-06-05 05:26:39.941883+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "959ca996a9d7"
down_revision: Union[str, None] = "add_prompt_to_agents"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 修改 creator_id 字段允许为空
    op.alter_column("agents", "creator_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 还原 creator_id 字段为不允许为空
    op.alter_column("agents", "creator_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
