"""add_background_to_agents

Revision ID: 20250606_120000
Revises: 24a617b81c38
Create Date: 2025-06-06 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250606_120000'
down_revision = '24a617b81c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('background', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'background')
    # ### end Alembic commands ### 