"""add sent_fallbacks_images column

Revision ID: 47eafda3e405
Revises: e5f6a7b8c9d1
Create Date: 2026-02-27 05:35:16.499624+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47eafda3e405'
down_revision: Union[str, None] = 'e5f6a7b8c9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('agent_followers')
    op.drop_column('agents', 'character_card_spec')
    op.drop_column('agents', 'character_card_data')
    op.add_column('chats', sa.Column('sent_fallback_images', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='已展示的兜底图片 image_id 列表，用于排除后续兜底候选'))
    op.alter_column('memory', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="记忆扩展字段；节日记忆使用 {'festival_name': str, 'festival_date': 'YYYY-MM-DD', 'llm_config': {model, temperature, max_tokens} 可选}",
               existing_comment="记忆扩展字段；节日记忆使用 {'festival_name': str, 'festival_data': 'YYYY-MM-DD'}",
               existing_nullable=True)
    op.alter_column('memory', 'extracted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='所属抽取批次时间（已废弃，仅兼容历史数据）',
               existing_comment='所属抽取批次时间',
               existing_nullable=False)
    op.alter_column('user_analytics_report', 'charts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='图表数据：new_users, conversation_rounds, user_rounds_distribution, users_hitting_limit, popular_agents, generated_images, daily_top_agents_by_rounds, daily_most_discussed_agent',
               existing_comment='图表数据：new_users, conversation_rounds, user_rounds_distribution, users_hitting_limit, popular_agents',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_analytics_report', 'charts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='图表数据：new_users, conversation_rounds, user_rounds_distribution, users_hitting_limit, popular_agents',
               existing_comment='图表数据：new_users, conversation_rounds, user_rounds_distribution, users_hitting_limit, popular_agents, generated_images, daily_top_agents_by_rounds, daily_most_discussed_agent',
               existing_nullable=True)
    op.alter_column('memory', 'extracted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='所属抽取批次时间',
               existing_comment='所属抽取批次时间（已废弃，仅兼容历史数据）',
               existing_nullable=False)
    op.alter_column('memory', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="记忆扩展字段；节日记忆使用 {'festival_name': str, 'festival_data': 'YYYY-MM-DD'}",
               existing_comment="记忆扩展字段；节日记忆使用 {'festival_name': str, 'festival_date': 'YYYY-MM-DD', 'llm_config': {model, temperature, max_tokens} 可选}",
               existing_nullable=True)
    op.drop_column('chats', 'sent_fallback_images')
    op.add_column('agents', sa.Column('character_card_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('character_card_spec', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('agent_followers',
    sa.Column('agent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('agent_followers_agent_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_followers_user_id_fkey')),
    sa.PrimaryKeyConstraint('agent_id', 'user_id', name=op.f('agent_followers_pkey'))
    )
    op.create_table('messages',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('TEXT', 'VOICE', 'IMAGE', name='messagetype'), autoincrement=False, nullable=True),
    sa.Column('sender_type', postgresql.ENUM('USER', 'AI', name='sendertype'), autoincrement=False, nullable=True),
    sa.Column('sender_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('chat_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('messages_agent_id_fkey')),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_messages_chat_id')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('messages_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###
