"""add companion_user_feedback table

Revision ID: 9eec6e4cafd1
Revises: f73e1b518bfe
Create Date: 2026-05-29 12:18:57.418672+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eec6e4cafd1'
down_revision: Union[str, None] = 'f73e1b518bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companion_user_feedback',
    sa.Column('id', sa.String(length=64), nullable=False, comment='反馈记录ID (uuid hex)'),
    sa.Column('user_id', sa.String(), nullable=False, comment='用户ID'),
    sa.Column('companion_id', sa.String(), nullable=False, comment='伴侣/Agent ID'),
    sa.Column('chat_id', sa.String(), nullable=False, comment='会话ID'),
    sa.Column('category', sa.String(length=64), nullable=False, comment='UserFeedbackCategory 枚举值'),
    sa.Column('feedback_text', sa.Text(), nullable=False, comment='跨多条消息推断出的反馈摘要'),
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='记录该反馈的 inner-tick 运行的 Inty trace_id'),
    sa.Column('user_msg_uuid', sa.String(length=64), nullable=True, comment='记录运行关联的 user_msg_uuid'),
    sa.Column('repro_context', sa.JSON(), nullable=True, comment='UserFeedbackReproContext: 用户原话与相关回复等复现锚点'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companion_user_feedback_companion_id'), 'companion_user_feedback', ['companion_id'], unique=False)
    op.create_index(op.f('ix_companion_user_feedback_trace_id'), 'companion_user_feedback', ['trace_id'], unique=False)
    op.create_index(op.f('ix_companion_user_feedback_user_id'), 'companion_user_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companion_user_feedback_user_id'), table_name='companion_user_feedback')
    op.drop_index(op.f('ix_companion_user_feedback_trace_id'), table_name='companion_user_feedback')
    op.drop_index(op.f('ix_companion_user_feedback_companion_id'), table_name='companion_user_feedback')
    op.drop_table('companion_user_feedback')
    # ### end Alembic commands ###
