"""github issue

Revision ID: b2d0fb5c7f6f
Revises: a0b3e0778673
Create Date: 2026-02-11 08:18:36.070981+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b2d0fb5c7f6f"
down_revision: Union[str, None] = "a0b3e0778673"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "report",
        sa.Column(
            "github_issue",
            sa.String(length=500),
            nullable=True,
            comment="关联的 GitHub issue URL",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report", "github_issue")
    # ### end Alembic commands ###
