"""add new tables for agentic companion

Revision ID: 512401673084
Revises: 20260324_120000
Create Date: 2026-04-14 08:06:30.246657+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '512401673084'
down_revision: Union[str, None] = '20260324_120000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companion_workspace_document_versions',
    sa.Column('sequence_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('record_uuid', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('companion_id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('document_kind', sa.String(length=64), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sequence_id'),
    sa.UniqueConstraint('record_uuid')
    )
    op.create_index('ix_companion_ws_doc_scope_kind_date_seq', 'companion_workspace_document_versions', ['user_id', 'companion_id', 'chat_id', 'document_kind', 'calendar_date', 'sequence_id'], unique=False)
    op.alter_column('memory', 'memory_type',
               existing_type=sa.VARCHAR(),
               comment='user_common | user_agent | festival | daily_bonding',
               existing_comment='user_common | user_agent | festival',
               existing_nullable=False)
    op.alter_column('memory', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="记忆扩展字段；节日记忆使用 {'festival_name': str, 'festival_date': 'YYYY-MM-DD', 'llm_config': {model, temperature, max_tokens} 可选}；日常记忆使用 {'local_date': 'YYYY-MM-DD', 'timezone': 'UTC', 'emotional_salience': 0.8, 'source_message_count': 12, 'risk_tier': 'low'}",
               existing_comment="记忆扩展字段；节日记忆使用 {'festival_name': str, 'festival_date': 'YYYY-MM-DD', 'llm_config': {model, temperature, max_tokens} 可选}",
               existing_nullable=True)
    op.alter_column('memory', 'delivery_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记忆提示首次投递到会话的时间，仅 memory_type=festival/daily_bonding 时使用',
               existing_comment='节日记忆提示首次投递到会话的时间，仅 memory_type=festival 时使用',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memory', 'delivery_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='节日记忆提示首次投递到会话的时间，仅 memory_type=festival 时使用',
               existing_comment='记忆提示首次投递到会话的时间，仅 memory_type=festival/daily_bonding 时使用',
               existing_nullable=True)
    op.alter_column('memory', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="记忆扩展字段；节日记忆使用 {'festival_name': str, 'festival_date': 'YYYY-MM-DD', 'llm_config': {model, temperature, max_tokens} 可选}",
               existing_comment="记忆扩展字段；节日记忆使用 {'festival_name': str, 'festival_date': 'YYYY-MM-DD', 'llm_config': {model, temperature, max_tokens} 可选}；日常记忆使用 {'local_date': 'YYYY-MM-DD', 'timezone': 'UTC', 'emotional_salience': 0.8, 'source_message_count': 12, 'risk_tier': 'low'}",
               existing_nullable=True)
    op.alter_column('memory', 'memory_type',
               existing_type=sa.VARCHAR(),
               comment='user_common | user_agent | festival',
               existing_comment='user_common | user_agent | festival | daily_bonding',
               existing_nullable=False)
    op.drop_index('ix_companion_ws_doc_scope_kind_date_seq', table_name='companion_workspace_document_versions')
    op.drop_table('companion_workspace_document_versions')
    # ### end Alembic commands ###
