"""add agentic companion input output queue tables

Revision ID: efcea1e32a72
Revises: 1a83f89c9a41
Create Date: 2026-06-15 06:58:12.340021+00:00
Revision source: alembic-cli

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Inty marker: generated by `alembic revision` via backend/alembic/script.py.mako.
# Agent-handwritten revisions must NOT include this constant.
INTY_REVISION_SOURCE = "alembic-cli"

# revision identifiers, used by Alembic.
revision: str = "efcea1e32a72"
down_revision: Union[str, None] = "1a83f89c9a41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agentic_companion_input_queue",
        sa.Column(
            "id", sa.String(), nullable=False, comment="Queue message id (uuid)"
        ),
        sa.Column(
            "user_id", sa.String(), nullable=False, comment="Inty human user id"
        ),
        sa.Column(
            "agent_id",
            sa.String(),
            nullable=False,
            comment="Inty companion agent id",
        ),
        sa.Column(
            "sequence_id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Monotonic ordering within scope",
        ),
        sa.Column(
            "status", sa.String(), nullable=False, comment="QueueStatus value"
        ),
        sa.Column(
            "channel",
            sa.String(),
            nullable=False,
            comment="CompanionRuntimeChannel value",
        ),
        sa.Column(
            "wire_id",
            sa.String(),
            nullable=False,
            comment="Opaque runtime wire id",
        ),
        sa.Column(
            "client_message_id",
            sa.String(),
            nullable=True,
            comment="Client-supplied message id when available",
        ),
        sa.Column(
            "text",
            sa.Text(),
            nullable=False,
            comment="User-visible inbound text",
        ),
        sa.Column(
            "batch_id",
            sa.String(),
            nullable=True,
            comment="Claim batch id when claimed by AgenticCompanion",
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agentic_companion_input_queue_scope_status_seq",
        "agentic_companion_input_queue",
        ["user_id", "agent_id", "status", "sequence_id"],
        unique=False,
    )
    op.create_table(
        "agentic_companion_output_queue",
        sa.Column(
            "id", sa.String(), nullable=False, comment="Queue message id (uuid)"
        ),
        sa.Column(
            "user_id", sa.String(), nullable=False, comment="Inty human user id"
        ),
        sa.Column(
            "agent_id",
            sa.String(),
            nullable=False,
            comment="Inty companion agent id",
        ),
        sa.Column(
            "sequence_id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Monotonic ordering within scope",
        ),
        sa.Column(
            "status", sa.String(), nullable=False, comment="QueueStatus value"
        ),
        sa.Column(
            "batch_id",
            sa.String(),
            nullable=False,
            comment="Input batch or synthetic turn batch id",
        ),
        sa.Column(
            "kind", sa.String(), nullable=False, comment="DownlinkKind value"
        ),
        sa.Column(
            "text",
            sa.Text(),
            nullable=False,
            comment="Assistant-visible text payload",
        ),
        sa.Column(
            "in_reply_to_input_ids_json",
            sa.Text(),
            server_default=sa.text("'[]'"),
            nullable=False,
            comment="JSON array of input queue ids",
        ),
        sa.Column("trace_id", sa.String(), nullable=True),
        sa.Column("langsmith_trace_id", sa.String(), nullable=True),
        sa.Column("langsmith_run_id", sa.String(), nullable=True),
        sa.Column("turn_recall", sa.Text(), nullable=True),
        sa.Column("delivery_channel", sa.String(), nullable=True),
        sa.Column("delivery_wire_id", sa.String(), nullable=True),
        sa.Column(
            "delivery_attempt_count",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agentic_companion_output_queue_batch_seq",
        "agentic_companion_output_queue",
        ["batch_id", "sequence_id"],
        unique=False,
    )
    op.create_index(
        "ix_agentic_companion_output_queue_scope_status_seq",
        "agentic_companion_output_queue",
        ["user_id", "agent_id", "status", "sequence_id"],
        unique=False,
    )
    op.alter_column(
        "agents",
        "readable_id",
        existing_type=sa.VARCHAR(length=8),
        comment="DEPRECATED: use Agent.id; legacy 8-digit display id",
        existing_comment="【已废弃】角色可读ID",
        existing_nullable=True,
    )
    op.alter_column(
        "agents",
        "status_line",
        existing_type=sa.VARCHAR(),
        comment="Short mood/tagline for chat header (iMate status line)",
        existing_comment="Short mood/tagline for chat header; updated by companion tools",
        existing_nullable=True,
    )
    op.alter_column(
        "ops_wechat_demo_bridges",
        "session_id",
        existing_type=sa.VARCHAR(),
        comment="Ops Weixin session UUID; WeixinChannelBinding.user_id",
        existing_comment="Ops demo session UUID; WeixinChannelBinding.user_id",
        existing_nullable=False,
    )
    op.alter_column(
        "ops_wechat_demo_bridges",
        "inty_api_base_url",
        existing_type=sa.VARCHAR(),
        comment="Inty HTTP API origin for companion",
        existing_comment="Inty HTTP API origin for companion WebSocket",
        existing_nullable=False,
    )
    op.alter_column(
        "ops_wechat_demo_bridges",
        "inty_jwt",
        existing_type=sa.TEXT(),
        comment="Bearer JWT for Inty companion auth",
        existing_comment="Bearer JWT for Inty WS auth (plaintext Ops demo)",
        existing_nullable=False,
    )
    op.alter_column(
        "ops_wechat_demo_bridges",
        "agent_id",
        existing_type=sa.VARCHAR(),
        comment="Inty companion agent_id",
        existing_comment="Inty companion agent_id on the WebSocket",
        existing_nullable=False,
    )
    op.alter_column(
        "ops_wechat_demo_bridges",
        "weixin_token",
        existing_type=sa.TEXT(),
        comment="iLink bot_token after QR; no API TTL — invalid when errcode=-14 on poll/send",
        existing_comment="iLink bot token (inline for restore without hermes files)",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "readable_id",
        existing_type=sa.VARCHAR(length=8),
        comment="DEPRECATED: use User.id; legacy 8-digit display id",
        existing_comment="【已废弃】用户可读ID",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "readable_id",
        existing_type=sa.VARCHAR(length=8),
        comment="【已废弃】用户可读ID",
        existing_comment="DEPRECATED: use User.id; legacy 8-digit display id",
        existing_nullable=True,
    )
    op.alter_column(
        "ops_wechat_demo_bridges",
        "weixin_token",
        existing_type=sa.TEXT(),
        comment="iLink bot token (inline for restore without hermes files)",
        existing_comment="iLink bot_token after QR; no API TTL — invalid when errcode=-14 on poll/send",
        existing_nullable=False,
    )
    op.alter_column(
        "ops_wechat_demo_bridges",
        "agent_id",
        existing_type=sa.VARCHAR(),
        comment="Inty companion agent_id on the WebSocket",
        existing_comment="Inty companion agent_id",
        existing_nullable=False,
    )
    op.alter_column(
        "ops_wechat_demo_bridges",
        "inty_jwt",
        existing_type=sa.TEXT(),
        comment="Bearer JWT for Inty WS auth (plaintext Ops demo)",
        existing_comment="Bearer JWT for Inty companion auth",
        existing_nullable=False,
    )
    op.alter_column(
        "ops_wechat_demo_bridges",
        "inty_api_base_url",
        existing_type=sa.VARCHAR(),
        comment="Inty HTTP API origin for companion WebSocket",
        existing_comment="Inty HTTP API origin for companion",
        existing_nullable=False,
    )
    op.alter_column(
        "ops_wechat_demo_bridges",
        "session_id",
        existing_type=sa.VARCHAR(),
        comment="Ops demo session UUID; WeixinChannelBinding.user_id",
        existing_comment="Ops Weixin session UUID; WeixinChannelBinding.user_id",
        existing_nullable=False,
    )
    op.alter_column(
        "agents",
        "status_line",
        existing_type=sa.VARCHAR(),
        comment="Short mood/tagline for chat header; updated by companion tools",
        existing_comment="Short mood/tagline for chat header (iMate status line)",
        existing_nullable=True,
    )
    op.alter_column(
        "agents",
        "readable_id",
        existing_type=sa.VARCHAR(length=8),
        comment="【已废弃】角色可读ID",
        existing_comment="DEPRECATED: use Agent.id; legacy 8-digit display id",
        existing_nullable=True,
    )
    op.drop_index(
        "ix_agentic_companion_output_queue_scope_status_seq",
        table_name="agentic_companion_output_queue",
    )
    op.drop_index(
        "ix_agentic_companion_output_queue_batch_seq",
        table_name="agentic_companion_output_queue",
    )
    op.drop_table("agentic_companion_output_queue")
    op.drop_index(
        "ix_agentic_companion_input_queue_scope_status_seq",
        table_name="agentic_companion_input_queue",
    )
    op.drop_table("agentic_companion_input_queue")
    # ### end Alembic commands ###
