"""add app ws queue delivery fields

Revision ID: d68e305bca69
Revises: 28ea966f0c57
Create Date: 2026-06-20 23:53:12.967180+00:00
Revision source: alembic-cli

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Inty marker: generated by `alembic revision` via backend/alembic/script.py.mako.
# Agent-handwritten revisions must NOT include this constant.
INTY_REVISION_SOURCE = "alembic-cli"

# revision identifiers, used by Alembic.
revision: str = "d68e305bca69"
down_revision: Union[str, None] = "28ea966f0c57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agentic_companion_input_queue",
        sa.Column(
            "local_id",
            sa.String(),
            nullable=True,
            comment="Client optimistic-bubble id echoed by App-WS downlink",
        ),
    )
    op.add_column(
        "agentic_companion_input_queue",
        sa.Column(
            "chat_history_user_row_id",
            sa.Integer(),
            nullable=True,
            comment="App visible-history user row id for downlink correlation",
        ),
    )
    op.add_column(
        "agentic_companion_output_queue",
        sa.Column(
            "tool_background_started",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Whether the foreground turn started a user-visible tool background leg",
        ),
    )
    op.add_column(
        "agentic_companion_output_queue",
        sa.Column(
            "generated_images_json",
            sa.Text(),
            server_default=sa.text("'[]'"),
            nullable=False,
            comment="JSON array of generated image refs emitted with this output line",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agentic_companion_output_queue", "generated_images_json")
    op.drop_column("agentic_companion_output_queue", "tool_background_started")
    op.drop_column("agentic_companion_input_queue", "chat_history_user_row_id")
    op.drop_column("agentic_companion_input_queue", "local_id")
    # ### end Alembic commands ###
