"""add companion runtime pause fields

Revision ID: 90d4e807585d
Revises: d68e305bca69
Create Date: 2026-06-21 03:13:12.115033+00:00
Revision source: alembic-cli

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Inty marker: generated by `alembic revision` via backend/alembic/script.py.mako.
# Agent-handwritten revisions must NOT include this constant.
INTY_REVISION_SOURCE = "alembic-cli"

# revision identifiers, used by Alembic.
revision: str = "90d4e807585d"
down_revision: Union[str, None] = "d68e305bca69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companion_bonds",
        sa.Column(
            "runtime_paused_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When this active bond's runtime was paused for cost control",
        ),
    )
    op.add_column(
        "companion_bonds",
        sa.Column(
            "last_resumed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When this active bond's runtime was last resumed",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companion_bonds", "last_resumed_at")
    op.drop_column("companion_bonds", "runtime_paused_at")
    # ### end Alembic commands ###
