"""rename output queue message_ids_json column

Revision ID: 28a322b5bbeb
Revises: 90d4e807585d
Create Date: 2026-06-24 19:03:15.118899+00:00
Revision source: alembic-cli

"""
from typing import Sequence, Union

from alembic import op

# Inty marker: generated by `alembic revision` via backend/alembic/script.py.mako.
# Agent-handwritten revisions must NOT include this constant.
INTY_REVISION_SOURCE = "alembic-cli"

# revision identifiers, used by Alembic.
revision: str = "28a322b5bbeb"
down_revision: Union[str, None] = "90d4e807585d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLE = "agentic_companion_output_queue"
_OLD_COLUMN = "in_reply_to_input_ids_json"
_NEW_COLUMN = "message_ids_json"


def upgrade() -> None:
    op.alter_column(
        _TABLE,
        _OLD_COLUMN,
        new_column_name=_NEW_COLUMN,
        comment="JSON array of input queue message ids",
    )


def downgrade() -> None:
    op.alter_column(
        _TABLE,
        _NEW_COLUMN,
        new_column_name=_OLD_COLUMN,
        comment="JSON array of input queue ids",
    )
