"""add llm config column

Revision ID: f055c1912687
Revises: 05dcb0c1c14c
Create Date: 2026-02-15 04:02:14.715260+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f055c1912687"
down_revision: Union[str, None] = "05dcb0c1c14c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "festival_memory_config",
        sa.Column(
            "llm_config",
            sa.JSON(),
            nullable=True,
            comment="LLM 模型配置 JSON，null 表示使用全局默认",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("festival_memory_config", "llm_config")
    # ### end Alembic commands ###
