"""add companion bonds

Revision ID: 28ea966f0c57
Revises: efcea1e32a72
Create Date: 2026-06-18 00:25:18.504601+00:00
Revision source: alembic-cli

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Inty marker: generated by `alembic revision` via backend/alembic/script.py.mako.
# Agent-handwritten revisions must NOT include this constant.
INTY_REVISION_SOURCE = "alembic-cli"

# revision identifiers, used by Alembic.
revision: str = "28ea966f0c57"
down_revision: Union[str, None] = "efcea1e32a72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companion_bonds",
        sa.Column(
            "id", sa.String(), nullable=False, comment="Bond row id (uuid)"
        ),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=False,
            comment="Inty human user id",
        ),
        sa.Column(
            "agent_id",
            sa.String(),
            nullable=False,
            comment="Inty companion agent id",
        ),
        sa.Column(
            "state",
            sa.Enum("ACTIVE", "INACTIVE", name="companionbondstate"),
            nullable=False,
            comment="CompanionBondState value",
        ),
        sa.Column(
            "inactive_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When this bond stopped being active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("companion_bonds")
    op.execute("DROP TYPE IF EXISTS companionbondstate")
    # ### end Alembic commands ###
