"""更新数据库表

Revision ID: a0b3e0778673
Revises: c0d9e8f7a6b5
Create Date: 2026-02-11 07:17:33.147378+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a0b3e0778673"
down_revision: Union[str, None] = "c0d9e8f7a6b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agents",
        "readable_id",
        existing_type=sa.VARCHAR(length=8),
        comment="【已废弃】角色可读ID",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_chat_history_deleted_at"),
        table_name="chat_history",
        postgresql_where="(deleted_at IS NOT NULL)",
    )
    op.create_index(
        op.f("ix_feedback_push_history_id"),
        "feedback_push_history",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_push_history_user_id"),
        "feedback_push_history",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "festival_memory_config",
        "festival_date",
        existing_type=sa.DATE(),
        comment="节日日期（该时区下的自然日）",
        existing_comment="节日日期",
        existing_nullable=False,
    )
    op.alter_column(
        "festival_memory_config",
        "run_at_date",
        existing_type=sa.DATE(),
        comment="执行日期（该时区下），须 >= festival_date",
        existing_comment="执行日期，须 >= festival_date",
        existing_nullable=True,
    )
    op.alter_column(
        "festival_memory_config",
        "run_at_hour",
        existing_type=sa.INTEGER(),
        comment="执行时刻（该时区下本地小时），0-23",
        existing_comment="执行时刻 UTC 小时，0-23",
        existing_nullable=True,
    )
    op.alter_column(
        "memory",
        "memory_type",
        existing_type=sa.VARCHAR(),
        comment="user_common | user_agent | festival",
        existing_comment="user_common | user_agent",
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_subscription_usage_user_type_date"),
        table_name="subscription_usage",
    )
    op.drop_index(
        op.f("ix_user_analytics_report_type_date"),
        table_name="user_analytics_report",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_user_analytics_report_type_date"),
        "user_analytics_report",
        ["report_type", "report_date"],
        unique=True,
    )
    op.create_index(
        op.f("ix_subscription_usage_user_type_date"),
        "subscription_usage",
        ["user_id", "usage_type", "usage_date"],
        unique=False,
    )
    op.alter_column(
        "memory",
        "memory_type",
        existing_type=sa.VARCHAR(),
        comment="user_common | user_agent",
        existing_comment="user_common | user_agent | festival",
        existing_nullable=False,
    )
    op.alter_column(
        "festival_memory_config",
        "run_at_hour",
        existing_type=sa.INTEGER(),
        comment="执行时刻 UTC 小时，0-23",
        existing_comment="执行时刻（该时区下本地小时），0-23",
        existing_nullable=True,
    )
    op.alter_column(
        "festival_memory_config",
        "run_at_date",
        existing_type=sa.DATE(),
        comment="执行日期，须 >= festival_date",
        existing_comment="执行日期（该时区下），须 >= festival_date",
        existing_nullable=True,
    )
    op.alter_column(
        "festival_memory_config",
        "festival_date",
        existing_type=sa.DATE(),
        comment="节日日期",
        existing_comment="节日日期（该时区下的自然日）",
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_feedback_push_history_user_id"),
        table_name="feedback_push_history",
    )
    op.drop_index(
        op.f("ix_feedback_push_history_id"), table_name="feedback_push_history"
    )
    op.create_index(
        op.f("ix_chat_history_deleted_at"),
        "chat_history",
        ["deleted_at"],
        unique=False,
        postgresql_where="(deleted_at IS NOT NULL)",
    )
    op.alter_column(
        "agents",
        "readable_id",
        existing_type=sa.VARCHAR(length=8),
        comment=None,
        existing_comment="【已废弃】角色可读ID",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
