"""agent_channel_endpoints table; drop ops_telegram_demo_bindings

Revision ID: 1a83f89c9a41
Revises: 20260612_120000
Create Date: 2026-06-12 07:31:20.389866+00:00
Revision source: alembic-cli

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# Inty marker: generated by `alembic revision` via backend/alembic/script.py.mako.
# Agent-handwritten revisions must NOT include this constant.
INTY_REVISION_SOURCE = "alembic-cli"

# revision identifiers, used by Alembic.
revision: str = "1a83f89c9a41"
down_revision: Union[str, None] = "20260612_120000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "agent_channel_endpoints",
        sa.Column(
            "id",
            sa.String(),
            nullable=False,
            comment="Endpoint row id (uuid)",
        ),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=False,
            comment="Inty human user id",
        ),
        sa.Column(
            "agent_id",
            sa.String(),
            nullable=False,
            comment="Inty companion agent id",
        ),
        sa.Column(
            "channel",
            sa.String(),
            nullable=False,
            comment="CompanionRuntimeChannel value (telegram, wechat_weixin, …)",
        ),
        sa.Column(
            "channel_address",
            sa.String(),
            nullable=False,
            comment="Opaque outbound routing key on this channel",
        ),
        sa.Column(
            "channel_user_id",
            sa.String(),
            nullable=False,
            comment="Opaque channel-side human identity for 1:1 bonding",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agent_id",
            "channel",
            name="uq_agent_channel_endpoints_agent_channel",
        ),
        sa.UniqueConstraint(
            "channel",
            "channel_address",
            name="uq_agent_channel_endpoints_channel_address",
        ),
        sa.UniqueConstraint(
            "channel",
            "channel_user_id",
            name="uq_agent_channel_endpoints_channel_user_id",
        ),
        sa.UniqueConstraint(
            "user_id",
            "channel",
            name="uq_agent_channel_endpoints_user_channel",
        ),
    )
    # Telegram private DM: chat_id equals sender user id; reuse for channel_user_id.
    op.execute(
        sa.text(
            """
            INSERT INTO agent_channel_endpoints (
                id,
                user_id,
                agent_id,
                channel,
                channel_address,
                channel_user_id,
                created_at,
                updated_at
            )
            SELECT
                gen_random_uuid()::text,
                user_id,
                agent_id,
                'telegram',
                telegram_chat_id,
                telegram_chat_id,
                created_at,
                updated_at
            FROM ops_telegram_demo_bindings
            """
        )
    )
    op.drop_table("ops_telegram_demo_bindings")


def downgrade() -> None:
    op.create_table(
        "ops_telegram_demo_bindings",
        sa.Column(
            "telegram_chat_id",
            sa.String(),
            nullable=False,
            comment="Telegram DM chat id; routing key for inbound getUpdates",
        ),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=False,
            comment="Inty guest user for this Telegram account",
        ),
        sa.Column(
            "agent_id",
            sa.String(),
            nullable=False,
            comment="Companion agent_id for this binding",
        ),
        sa.Column(
            "chat_id",
            sa.String(),
            nullable=False,
            comment="Inty chat row id (MemoryStore scope)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("telegram_chat_id"),
    )
    op.drop_table("agent_channel_endpoints")
