"""add system_notification_sent_at to memory

Revision ID: 05dcb0c1c14c
Revises: e2f3a4b5c6d7
Create Date: 2026-02-14 05:49:46.659236+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05dcb0c1c14c'
down_revision: Union[str, None] = 'e2f3a4b5c6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory', sa.Column('system_notification_sent_at', sa.DateTime(timezone=True), nullable=True, comment='节日记忆 system 推送发送时间，仅 memory_type=festival 时使用'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory', 'system_notification_sent_at')
    # ### end Alembic commands ###
