from app.core.config import global_config_loaded_from_config_yaml
from app.external_services.android_publisher import create_android_publisher_service


service_account_key = global_config_loaded_from_config_yaml.google_play.service_account_key
android_publisher_service = create_android_publisher_service(service_account_key)