"""Track/Phase prompt domain model and composed system-message assembly.

Settled ``user_turn`` is the first track migrated off ``build_system_messages`` bool
routing. Other user-visible tracks (``proactive_chat``, ``scheduled_activity``,
``sign_on_greeting``) and hidden cognition tracks (``monolog``, ``autonomy``,
``dreaming``) remain on legacy entrypoints until follow-up issues (!3453, !3398).

Generated by Cursor agent for user-turn composed prompt assembly (PR 1).
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from app.core.companion_harness.companion.models import ContextMeta
from app.core.companion_harness.companion.prompts.system_messages import (
    _auxiliary_system_messages,
    _doctrine_system_messages,
    _dual_llm_chat_structured_output_contract_text,
    _infer_time_zone_prompt_slice,
    _living_sphere_persistence_clause,
    _output_contract_text_chat_branch_mirrored_tools,
    _output_contract_text_with_tools,
    _system_message,
)
from app.core.companion_harness.experience_profile.context_mode import (
    experience_profile_injects_private_memory,
    experience_profile_system_clause,
)
from app.core.companion_harness.experience_profile.experience_directives import (
    experience_directives_system_clause,
)
from app.core.companion_harness.memory.memory_taxonomy import (
    COMPANIONSHIP_SYSTEM_HEADING,
    MEMORY_SYSTEM_HEADING_DAILY_GIST,
    MEMORY_SYSTEM_HEADING_SEMANTIC,
)
from app.core.companion_harness.prompting.bundle import PromptBundle


class Track(StrEnum):
    """Sustained companion activity stream routed through composed prompt assembly."""

    USER_TURN = "user_turn"
    # TODO(!3453): proactive_chat, scheduled_activity, sign_on_greeting (user-visible).
    # TODO(!3453): monolog, autonomy, dreaming (hidden cognition).


class Phase(StrEnum):
    """Phase within a user-visible track (e.g. bootstrap vs settled on user_turn)."""

    SETTLED = "settled"
    BOOTSTRAP = "bootstrap"


class UserTurnLeg(StrEnum):
    """Which system stack variant applies within settled ``user_turn``."""

    SINGLE_LLM = "single_llm"
    DUAL_LLM_CHAT = "dual_llm_chat"


def _require_settled_phase(phase: Phase) -> None:
    if phase != Phase.SETTLED:
        raise NotImplementedError(
            "TODO(!3453): user_turn bootstrap phase stays on legacy "
            "build_system_messages_for_bootstrap_track until next migration"
        )


def _capability_settled_single_llm_system_messages(
    bundle: PromptBundle,
) -> list[dict[str, Any]]:
    """Settled single-LLM user_turn: harness + channels + tools when tools_md present."""
    out: list[dict[str, Any]] = []
    if bundle.tools_md.strip():
        if bundle.harness_md.strip():
            out.append(_system_message(bundle.harness_md.strip()))
        if bundle.channels_md.strip():
            out.append(_system_message(bundle.channels_md.strip()))
        out.append(_system_message(bundle.tools_md.strip()))
    return out


def _capability_settled_dual_chat_leg_system_messages() -> list[dict[str, Any]]:
    """Settled dual-LLM chat leg: API omits tools; capability package slices withheld."""
    return []


def _persona_settled_user_turn_system_messages(
    *,
    bundle: PromptBundle,
    context: ContextMeta,
    include_significance_perception_slice: bool,
) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = [
        _system_message(bundle.identity.strip()),
        _system_message(bundle.soul.strip()),
        _system_message(bundle.style_md.strip()),
    ]
    if bundle.companionship_md.strip():
        out.append(
            _system_message(
                COMPANIONSHIP_SYSTEM_HEADING + bundle.companionship_md.strip()
            )
        )
    if bundle.techno_core_md.strip():
        out.append(_system_message(bundle.techno_core_md.strip()))
    if bundle.living_sphere_md.strip():
        out.append(_system_message(bundle.living_sphere_md.strip()))
    out.append(_system_message(_living_sphere_persistence_clause()))
    out.append(_system_message(bundle.user_md.strip()))
    if include_significance_perception_slice:
        out.append(_system_message(bundle.significance_perception_md.strip()))
    if experience_profile_injects_private_memory(context.context_mode):
        if bundle.memory_daily_today_md.strip():
            out.append(
                _system_message(
                    MEMORY_SYSTEM_HEADING_DAILY_GIST
                    + bundle.memory_daily_today_md.strip()
                )
            )
        if bundle.memory_md.strip():
            out.append(
                _system_message(
                    MEMORY_SYSTEM_HEADING_SEMANTIC + bundle.memory_md.strip()
                )
            )
    return out


def _output_settled_single_llm_system_messages() -> list[dict[str, Any]]:
    return [
        _system_message(
            _output_contract_text_with_tools(tool_side_compact=False)
        )
    ]


def _output_settled_dual_chat_leg_system_messages() -> list[dict[str, Any]]:
    return [
        _system_message(_output_contract_text_chat_branch_mirrored_tools()),
        _system_message(_dual_llm_chat_structured_output_contract_text()),
    ]


def _contextual_settled_user_turn_system_messages(
    context: ContextMeta,
) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = [
        _system_message(experience_profile_system_clause(context.context_mode))
    ]
    directive_clause = experience_directives_system_clause(
        context.experience_directives
    )
    if directive_clause is not None:
        out.append(_system_message(directive_clause))
    out.append(_system_message(_infer_time_zone_prompt_slice()))
    return out


def build_settled_user_turn_single_llm_system_messages(
    bundle: PromptBundle,
    context: ContextMeta,
    *,
    phase: Phase = Phase.SETTLED,
) -> list[dict[str, Any]]:
    """Settled ``user_turn`` single-LLM in-turn tools system prefix."""
    _require_settled_phase(phase)
    out: list[dict[str, Any]] = []
    out.extend(_doctrine_system_messages())
    out.extend(_auxiliary_system_messages())
    out.extend(_capability_settled_single_llm_system_messages(bundle))
    out.extend(
        _persona_settled_user_turn_system_messages(
            bundle=bundle,
            context=context,
            include_significance_perception_slice=False,
        )
    )
    out.extend(_output_settled_single_llm_system_messages())
    out.extend(_contextual_settled_user_turn_system_messages(context))
    return out


def build_settled_user_turn_dual_chat_leg_system_messages(
    bundle: PromptBundle,
    context: ContextMeta,
    *,
    phase: Phase = Phase.SETTLED,
) -> list[dict[str, Any]]:
    """Settled ``user_turn`` dual-LLM foreground chat leg system prefix."""
    _require_settled_phase(phase)
    out: list[dict[str, Any]] = []
    out.extend(_doctrine_system_messages())
    out.extend(_auxiliary_system_messages())
    out.extend(_capability_settled_dual_chat_leg_system_messages())
    out.extend(
        _persona_settled_user_turn_system_messages(
            bundle=bundle,
            context=context,
            include_significance_perception_slice=True,
        )
    )
    out.extend(_output_settled_dual_chat_leg_system_messages())
    out.extend(_contextual_settled_user_turn_system_messages(context))
    return out
