"""Phase prompt domain model and bool-free system-message slice builders.

Single-LLM settled+bootstrap assembly lives in ``PromptBuilder``; dual-LLM legs
compose via ``prompting.recipe`` (#3453).

Generated by Cursor agent for user-turn composed prompt assembly (PR 1).
"""

from __future__ import annotations

from typing import Any

from app.core.companion_harness.companion.models import ContextMeta
from app.core.companion_harness.companion.bootstrap import (
    build_bootstrap_tool_call_section,
    build_interactive_bootstrap_template_reference_parts,
    load_bootstrap_spec_text,
)
from app.core.companion_harness.prompting.system_messages import (
    _auxiliary_system_messages,
    _doctrine_system_messages,
    _dual_llm_chat_structured_output_contract_text,
    _living_sphere_persistence_clause,
    _output_contract_text_chat_branch_mirrored_tools,
    _output_contract_text_interactive_bootstrap_tools,
    _output_contract_text_with_tools,
    _system_message,
)
from app.core.companion_harness.experience_profile.context_mode import (
    experience_profile_injects_private_memory,
)
from app.core.companion_harness.memory.memory_taxonomy import (
    COMPANIONSHIP_SYSTEM_HEADING,
    MEMORY_SYSTEM_HEADING_DAILY_GIST,
    MEMORY_SYSTEM_HEADING_SEMANTIC,
)
from app.core.companion_harness.prompting.bundle import PromptBundle
from app.core.companion_harness.prompting.phase import Phase


def _capability_settled_single_llm_system_messages(
    bundle: PromptBundle,
) -> list[dict[str, Any]]:
    """Settled single-LLM user_turn: harness + channels + tools when tools_md present."""
    out: list[dict[str, Any]] = []
    if bundle.tools_md.strip():
        if bundle.harness_md.strip():
            out.append(_system_message(bundle.harness_md.strip()))
        if bundle.channels_md.strip():
            out.append(_system_message(bundle.channels_md.strip()))
        out.append(_system_message(bundle.tools_md.strip()))
    return out


def _capability_settled_dual_chat_leg_system_messages() -> list[dict[str, Any]]:
    """Settled dual-LLM chat leg: API omits tools; capability package slices withheld."""
    return []


def _persona_settled_user_turn_system_messages(
    *,
    bundle: PromptBundle,
    context: ContextMeta,
    include_significance_perception_slice: bool,
) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = [
        _system_message(bundle.identity.strip()),
        _system_message(bundle.soul.strip()),
        _system_message(bundle.style_md.strip()),
    ]
    if bundle.companionship_md.strip():
        out.append(
            _system_message(
                COMPANIONSHIP_SYSTEM_HEADING + bundle.companionship_md.strip()
            )
        )
    if bundle.techno_core_md.strip():
        out.append(_system_message(bundle.techno_core_md.strip()))
    if bundle.living_sphere_md.strip():
        out.append(_system_message(bundle.living_sphere_md.strip()))
    out.append(_system_message(_living_sphere_persistence_clause()))
    out.append(_system_message(bundle.user_md.strip()))
    if include_significance_perception_slice:
        out.append(_system_message(bundle.significance_perception_md.strip()))
    if experience_profile_injects_private_memory(context.context_mode):
        if bundle.memory_daily_today_md.strip():
            out.append(
                _system_message(
                    MEMORY_SYSTEM_HEADING_DAILY_GIST
                    + bundle.memory_daily_today_md.strip()
                )
            )
        if bundle.memory_md.strip():
            out.append(
                _system_message(
                    MEMORY_SYSTEM_HEADING_SEMANTIC + bundle.memory_md.strip()
                )
            )
    return out


def _output_settled_single_llm_system_messages() -> list[dict[str, Any]]:
    return [
        _system_message(
            _output_contract_text_with_tools(tool_side_compact=False)
        )
    ]


def _output_settled_dual_chat_leg_system_messages() -> list[dict[str, Any]]:
    return [
        _system_message(_output_contract_text_chat_branch_mirrored_tools()),
        _system_message(_dual_llm_chat_structured_output_contract_text()),
    ]


def _capability_bootstrap_single_llm_system_messages() -> list[dict[str, Any]]:
    """Bootstrap single-LLM user_turn: capability package slices suppressed."""
    return []


def _persona_bootstrap_user_turn_system_messages(
    *,
    bundle: PromptBundle,
    context: ContextMeta,
) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = [
        _system_message(bundle.identity.strip()),
        _system_message(bundle.soul.strip()),
        _system_message(bundle.style_md.strip()),
    ]
    if bundle.techno_core_md.strip():
        out.append(_system_message(bundle.techno_core_md.strip()))
    if bundle.living_sphere_md.strip():
        out.append(_system_message(bundle.living_sphere_md.strip()))
    out.append(_system_message(_living_sphere_persistence_clause()))
    out.append(_system_message(bundle.user_md.strip()))
    if experience_profile_injects_private_memory(context.context_mode):
        if bundle.memory_daily_today_md.strip():
            out.append(
                _system_message(
                    MEMORY_SYSTEM_HEADING_DAILY_GIST
                    + bundle.memory_daily_today_md.strip()
                )
            )
        if bundle.memory_md.strip():
            out.append(
                _system_message(
                    MEMORY_SYSTEM_HEADING_SEMANTIC + bundle.memory_md.strip()
                )
            )
    out.append(_system_message(load_bootstrap_spec_text()))
    out.append(_system_message(build_bootstrap_tool_call_section()))
    for block in build_interactive_bootstrap_template_reference_parts():
        out.append(_system_message(block))
    return out


def _output_bootstrap_single_llm_system_messages() -> list[dict[str, Any]]:
    return [
        _system_message(_output_contract_text_interactive_bootstrap_tools())
    ]
