"""IM channels delegate inner-tick delivery to the scope output pump.

Generated by Cursor agent for the Stage-1 AgenticLoop convergence review.
"""

from __future__ import annotations

from unittest.mock import AsyncMock, patch

import pytest

from app.core.companion_harness.companion.models import CompanionTurnResult
from app.schemas.chat import ChatCompletionRequest, ChatMessage
from app.schemas.chat_websocket import ChatWsCompanionWireMessageMetaData
from app.services.agentic_companion.inner_tick_deliver import (
    InnerTickVisibleDeliverInput,
    deliver_visible_inner_tick_turn,
)
from app.services.agentic_companion.inner_tick_delivery import (
    inner_tick_delivery_for_telegram,
)


def _deliver_input(
    *,
    delivery,
    output_message_ids: tuple[str, ...],
) -> InnerTickVisibleDeliverInput:
    return InnerTickVisibleDeliverInput(
        delivery=delivery,
        session_id="session-1",
        agent_id="agent-1",
        chat_row_agent_id="agent-1",
        ws_conn_id="conn-1",
        preset_uid="uid-1",
        transcript_user_text="[proactive]",
        companion_turn=CompanionTurnResult(
            assistant_text="proactive hello",
            output_message_ids=output_message_ids,
        ),
        stub_request=ChatCompletionRequest(
            messages=[ChatMessage(role="user", content="[proactive]")],
            message_id="uid-1",
        ),
        user_wire_meta=ChatWsCompanionWireMessageMetaData(source="inner_tick"),
        companion_scheduled_reminder=None,
        scheduled_task_id=None,
        log_label="test_inner_tick",
        skip_user_history=True,
    )


@pytest.mark.asyncio
async def test_im_channel_skips_direct_send_when_queue_rows_exist() -> None:
    sent: list[str] = []

    async def sink(text: str) -> None:
        sent.append(text)

    delivery = inner_tick_delivery_for_telegram(sink)
    with patch(
        "app.services.agentic_companion.inner_tick_deliver."
        "chat_history_service.add_ai_message_sync_async",
        new=AsyncMock(return_value=101),
    ) as add_ai:
        delivered = await deliver_visible_inner_tick_turn(
            _deliver_input(
                delivery=delivery,
                output_message_ids=("out-row-1",),
            )
        )

    assert delivered is True
    add_ai.assert_awaited_once()
    assert sent == []


@pytest.mark.asyncio
async def test_delivery_none_persists_history_without_channel_send() -> None:
    with (
        patch(
            "app.services.agentic_companion.inner_tick_deliver."
            "chat_history_service.add_user_message_async",
            new=AsyncMock(),
        ) as add_user,
        patch(
            "app.services.agentic_companion.inner_tick_deliver."
            "chat_history_service.add_ai_message_sync_async",
            new=AsyncMock(return_value=102),
        ) as add_ai,
        patch(
            "app.services.agentic_companion.inner_tick_deliver."
            "deliver_inner_tick_assistant",
            new=AsyncMock(),
        ) as channel_send,
    ):
        delivered = await deliver_visible_inner_tick_turn(
            InnerTickVisibleDeliverInput(
                delivery=None,
                session_id="session-1",
                agent_id="agent-1",
                chat_row_agent_id="agent-1",
                ws_conn_id="scope_inner_tick_worker",
                preset_uid="uid-1",
                transcript_user_text="[scheduled reminder]",
                companion_turn=CompanionTurnResult(
                    assistant_text="reminder text",
                    output_message_ids=("out-1",),
                ),
                stub_request=ChatCompletionRequest(
                    messages=[ChatMessage(role="user", content="[scheduled]")],
                    message_id="uid-1",
                ),
                user_wire_meta=ChatWsCompanionWireMessageMetaData(
                    source="inner_tick"
                ),
                companion_scheduled_reminder=True,
                scheduled_task_id="task-1",
                log_label="scope_scheduled_reminder",
                skip_user_history=False,
            )
        )
    assert delivered is True
    add_user.assert_awaited_once()
    add_ai.assert_awaited_once()
    channel_send.assert_not_awaited()
