"""Inner-tick visible turn persists chat_history only (pump owns channel delivery).

Generated by Cursor agent for #3398 P3.
"""

from __future__ import annotations

import pytest

from app.core.companion_harness.companion.models import CompanionTurnResult
from app.schemas.chat_websocket import ChatWsCompanionWireMessageMetaData
from app.services.agentic_companion import inner_tick_deliver as mod
from app.services.agentic_companion.inner_tick_deliver import (
    InnerTickVisiblePersistInput,
    persist_visible_inner_tick_turn,
)


class _RecordingChatHistory:
    def __init__(self) -> None:
        self.user_rows: list[tuple[str, str, dict]] = []
        self.ai_rows: list[tuple[str, str, str, dict]] = []

    async def add_user_message_async(
        self, session_id: str, text: str, *, meta_data: dict
    ) -> None:
        self.user_rows.append((session_id, text, meta_data))

    async def add_ai_message_sync_async(
        self,
        session_id: str,
        text: str,
        *,
        agent_id: str,
        meta_data: dict,
    ) -> int:
        self.ai_rows.append((session_id, text, agent_id, meta_data))
        return len(self.ai_rows)


def _persist_input(
    *,
    output_message_ids: tuple[str, ...],
) -> InnerTickVisiblePersistInput:
    return InnerTickVisiblePersistInput(
        session_id="session-1",
        chat_row_agent_id="agent-1",
        preset_uid="uid-1",
        transcript_user_text="[proactive]",
        companion_turn=CompanionTurnResult(
            assistant_text="proactive hello",
            output_message_ids=output_message_ids,
        ),
        user_wire_meta=ChatWsCompanionWireMessageMetaData(source="inner_tick"),
        companion_scheduled_reminder=None,
        scheduled_task_id=None,
        log_label="test_inner_tick",
        skip_user_history=True,
    )


@pytest.mark.asyncio
async def test_persist_visible_inner_tick_turn_writes_ai_history(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    history = _RecordingChatHistory()
    monkeypatch.setattr(mod, "chat_history_service", history)
    delivered = await persist_visible_inner_tick_turn(
        _persist_input(output_message_ids=("out-row-1",))
    )
    assert delivered is True
    assert len(history.ai_rows) == 1
    assert history.ai_rows[0][1] == "proactive hello"
    assert history.user_rows == []


@pytest.mark.asyncio
async def test_persist_visible_inner_tick_turn_writes_user_and_ai_history(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    history = _RecordingChatHistory()
    monkeypatch.setattr(mod, "chat_history_service", history)
    delivered = await persist_visible_inner_tick_turn(
        InnerTickVisiblePersistInput(
            session_id="session-1",
            chat_row_agent_id="agent-1",
            preset_uid="uid-1",
            transcript_user_text="[scheduled reminder]",
            companion_turn=CompanionTurnResult(
                assistant_text="reminder text",
                output_message_ids=("out-1",),
            ),
            user_wire_meta=ChatWsCompanionWireMessageMetaData(
                source="inner_tick"
            ),
            companion_scheduled_reminder=True,
            scheduled_task_id="task-1",
            log_label="scope_scheduled_reminder",
            skip_user_history=False,
        )
    )
    assert delivered is True
    assert len(history.user_rows) == 1
    assert len(history.ai_rows) == 1


@pytest.mark.asyncio
async def test_persist_visible_inner_tick_turn_returns_false_for_blank_reply(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    history = _RecordingChatHistory()
    monkeypatch.setattr(mod, "chat_history_service", history)
    delivered = await persist_visible_inner_tick_turn(
        InnerTickVisiblePersistInput(
            session_id="session-1",
            chat_row_agent_id="agent-1",
            preset_uid="uid-1",
            transcript_user_text="[monolog]",
            companion_turn=CompanionTurnResult(
                assistant_text="",
                output_message_ids=(),
            ),
            user_wire_meta=ChatWsCompanionWireMessageMetaData(
                source="inner_tick"
            ),
            companion_scheduled_reminder=None,
            scheduled_task_id=None,
            log_label="monolog",
            skip_user_history=True,
        )
    )
    assert delivered is False
    assert history.ai_rows == []
