"""Shared fake LLM envelope payloads for companion turn tests (generated by Cursor agent)."""

from __future__ import annotations

import json
from types import SimpleNamespace
from typing import Any


def envelope_json(
    *,
    user_facing_reply: str,
    importance_round: int = 5,
    importance_user_message: int = 5,
    importance_assistant_message: int = 5,
    output_to_user: bool = True,
) -> str:
    return json.dumps(
        {
            "user_facing_reply": user_facing_reply,
            "importance_round": importance_round,
            "importance_user_message": importance_user_message,
            "importance_assistant_message": importance_assistant_message,
            "output_to_user": output_to_user,
        },
        ensure_ascii=False,
    )


def envelope_response(
    *,
    user_facing_reply: str,
    tool_calls: list[Any] | None = None,
    importance_round: int = 5,
    importance_user_message: int = 5,
    importance_assistant_message: int = 5,
    output_to_user: bool = True,
) -> SimpleNamespace:
    content = envelope_json(
        user_facing_reply=user_facing_reply,
        importance_round=importance_round,
        importance_user_message=importance_user_message,
        importance_assistant_message=importance_assistant_message,
        output_to_user=output_to_user,
    )
    finish_reason = "tool_calls" if tool_calls else "stop"
    message = SimpleNamespace(content=content, tool_calls=tool_calls)
    return SimpleNamespace(
        choices=[SimpleNamespace(message=message, finish_reason=finish_reason)],
        model="test-model",
        usage=None,
    )
