name: Build and deploy inty backend

on:
  push:
    branches:
      - main
    paths:
      - "app/**/*.py"

  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: The environment to deploy to
        required: true
        default: dev

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment || 'dev' }}
  # Do not cancel in-progress builds.
  cancel-in-progress: false

env:
  INTY_SERVER_IMAGE: ghcr.io/nascentcore/inty-backend/inty-server
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      # Push to ghcr.io
      packages: write
      # Checkout repository
      contents: read

    environment: ${{ inputs.environment || 'dev' }}
    
    steps:
    - id: set-environment
      run: |
        echo "environment=${{ inputs.environment || 'dev' }}" >> $GITHUB_OUTPUT

    - uses: actions/checkout@v4

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/setup-buildx-action@v3
      with:
        cache-binary: true
        
    - id: build-docker-image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.INTY_SERVER_IMAGE }}:${{ github.ref_name }}
        
    - name: Deploy to ${{ steps.set-environment.outputs.environment }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_SERVER_HOST }}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_SSH_KEY }}
        script: |
          sudo docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          sudo docker pull ${{ env.INTY_SERVER_IMAGE }}@${{ steps.build-docker-image.outputs.digest }}
          sudo docker stop inty-backend-${{ steps.set-environment.outputs.environment }} || true
          sudo docker rm inty-backend-${{ steps.set-environment.outputs.environment }} || true
          sudo docker run --detach \
            --name inty-backend-${{ steps.set-environment.outputs.environment }} \
            --restart unless-stopped \
            --publish ${{ vars.SERVICE_PORT }}:8000 \
            --env LANGCHAIN_TRACING_V2=true \
            --env LANGCHAIN_PROJECT=inty-backend-${{ steps.set-environment.outputs.environment }} \
            --env LANGCHAIN_API_KEY=${{ secrets.LANGCHAIN_API_KEY }} \
            --label environment=${{ steps.set-environment.outputs.environment }} \
            --log-opt labels=environment \
            --volume /opt/inty-${{ steps.set-environment.outputs.environment }}/config.yaml:/config.yaml \
            --volume /opt/inty-${{ steps.set-environment.outputs.environment }}/inty-backend-key.json:/inty-backend-key.json \
            --volume /opt/inty-${{ steps.set-environment.outputs.environment }}/inty-firebase-key.json:/inty-firebase-key.json \
            ${{ env.INTY_SERVER_IMAGE }}@${{ steps.build-docker-image.outputs.digest }}

    - name: Sanity check
      run: |
        curl -s --fail --retry 5 --retry-delay 5 ${{ vars.SERVICE_PUBLIC_URL }}

    - name: Write summary
      run: |
        echo "## Build and deploy"
        echo "GitHub ref: ${{ github.ref }}"
        echo "Deployed to ${{ steps.set-environment.outputs.environment }} for ${{ vars.SERVICE_PUBLIC_URL }}" >> $GITHUB_STEP_SUMMARY
