name: Build and deploy Inty backend

on:
  push:
    branches:
      - main
    paths:
      # 后端代码
      - "app/**/*.py"
      - "alembic/**/*.py"
      # 开发环境配置文件
      - "devops/config.yaml.dev"
      # 评测系统
      - "evaluation/**/*.{ts,tsx,js,jsx,css,scss,less,html,json,svg,png,jpg,jpeg,ico,webp}"
      - "evaluation/tsconfig.json"
      - "evaluation/tsconfig.node.json"
      - "evaluation/package.json"
      - "evaluation/package-lock.json"
      - "evaluation/vite.config.ts"
      - "evaluation/vitest.config.ts"
      - "evaluation/index.html"
      - "build_evaluation.sh"
      - "Dockerfile"
      - ".github/workflows/build_and_deploy.yml"

  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: The environment to deploy to
        required: true
        default: dev

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment || 'dev' }}
  # Do not cancel in-progress builds.
  cancel-in-progress: false

env:
  INTY_SERVER_IMAGE: ghcr.io/nascentcore/inty-backend/inty-server

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      # Push to ghcr.io
      packages: write
      # Checkout repository
      contents: read

    # 自动运行的情况下，inputs.environment 为空，因此需要额外设置
    environment: ${{ inputs.environment || 'dev' }}

    steps:
      - id: set-environment
        run: |
          echo "environment=${{ inputs.environment || 'dev' }}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3
        with:
          cache-binary: true

      - id: build-docker-image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.INTY_SERVER_IMAGE }}:${{ github.ref_name }}-${{ steps.set-environment.outputs.environment }}
          # https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CONFIG_FILE=devops/config.yaml.${{ steps.set-environment.outputs.environment }}

      - name: Deploy to ${{ steps.set-environment.outputs.environment }}
        uses: appleboy/ssh-action@master
        # 这个限制这一步最长时间，同时内部有一个等待的循环，从而保证不会超时。
        timeout-minutes: 2
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          # TODO: Replace with script_path using GEMINI_DEPLOY_INTY_BACKEND.sh
          script: |
            sudo docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            sudo docker pull ${{ env.INTY_SERVER_IMAGE }}@${{ steps.build-docker-image.outputs.digest }}
            sudo docker stop inty-backend-${{ steps.set-environment.outputs.environment }} || true
            sudo docker rm inty-backend-${{ steps.set-environment.outputs.environment }} || true
            # log-driver: https://docs.docker.com/engine/logging/drivers/gcplogs/
            #   运行于 gcp 环境，docker engine 探测 gcp 环境信息，相关设置都自动提取
            #   https://docs.docker.com/engine/logging/drivers/gcplogs/#gcplogs-options
            # LANGCHAIN_* 相关环境变量应该不需要设置，已经在代码中强制设置，以后考虑清理
            # https://github.com/NascentCore/inty/blob/ef9c9735c62a9cb2d6be4b2414bebed410f1ff56/app/core/config.py#L267
            sudo docker run --detach --log-driver=gcplogs \
              --name inty-backend-${{ steps.set-environment.outputs.environment }} \
              --restart unless-stopped \
              --publish ${{ vars.SERVICE_PORT_ON_HOST }}:8000 \
              --env LANGCHAIN_TRACING_V2=true \
              --env LANGCHAIN_PROJECT=inty-backend-${{ steps.set-environment.outputs.environment }} \
              --env LANGCHAIN_API_KEY=${{ secrets.LANGCHAIN_API_KEY }} \
              --label application=inty-backend \
              --label environment=${{ steps.set-environment.outputs.environment }} \
              --log-opt labels=application,environment \
              --volume /opt/inty-${{ steps.set-environment.outputs.environment }}/inty-backend-key.json:/inty-backend-key.json \
              --volume /opt/inty-${{ steps.set-environment.outputs.environment }}/inty-firebase-key.json:/inty-firebase-key.json \
              ${{ env.INTY_SERVER_IMAGE }}@${{ steps.build-docker-image.outputs.digest }}
              echo "Waiting for application startup..."
              while ! sudo docker logs inty-backend-${{ steps.set-environment.outputs.environment }} 2>&1 | grep -q "Application startup complete"
              do
              sleep 1
              done
              if [ $? -eq 0 ]; then
                echo "Application startup complete detected!"
              else
                echo "Timeout waiting for application startup"
                exit 1
              fi

      - name: Sanity check
        run: |
          curl --verbose --fail --retry 5 --retry-delay 5 ${{ vars.SERVICE_PUBLIC_URL }}

      - name: Write summary
        run: |
          echo "## Build and deploy"
          echo "GitHub ref: ${{ github.ref }}"
          echo "Deployed to ${{ steps.set-environment.outputs.environment }} for ${{ vars.SERVICE_PUBLIC_URL }}" >> $GITHUB_STEP_SUMMARY
