# 构建 release 构建类型并上传到 Google Play Internal Testing 轨道。
name: Release - Build and upload aab to Google Play internal testing track

on:
  workflow_dispatch:

  schedule:
    # 1 am UTC, 9 am Beijing time, 6 pm PST.
    - cron: "0 1 * * *"

jobs:
  build-apk:
    runs-on: yaxiong-zhao
    permissions:
      contents: read
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Gradle dependencies and build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android_app/.gradle
            android_app/build
            android_app/app/build
            android_app/core/common/build
            android_app/core/data/build
            android_app/core/design/build
            android_app/core/firebase/build
            android_app/library/network/build
            android_app/library/utils/build
          # https://github.com/actions/cache/blob/main/examples.md#java---gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-

      - name: Create Google Play service account key
        env:
          GOOGLE_PLAY_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GOOGLE_PLAY_SERVICE_ACCOUNT_KEY" > service-account-key.json

      - name: Build release bundle and APK
        run: |
          cd android_app
          ./gradlew bundleRelease --stacktrace --info

      - id: gen-release-info
        run: |
          cd android_app
          echo "version_name_with_commit_id=$(./gradlew printVersionInfo | grep 'Version name with suffix: ' | awk -F': ' '{print $2}')" >> $GITHUB_OUTPUT
          echo "release_name=$(./gradlew printVersionInfo | grep 'Version name with suffix: ' | awk -F': ' '{print $2}' | sed 's/ (/-/; s/)//')" >> $GITHUB_OUTPUT

      - name: Upload release bundle to Google Play internal testing
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service-account-key.json
          packageName: com.ai.intellimate
          releaseFiles: android_app/app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed
          releaseName: ${{ steps.gen-release-info.outputs.release_name }}
          changesNotSentForReview: true

      - id: create-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.gen-release-info.outputs.release_name }}
          draft: false
          prerelease: false
          files: |
            android_app/app/build/outputs/apk/release/app-release.apk
          generate_release_notes: true
          make_latest: true
          fail_on_unmatched_files: false

      - name: Notify Feishu group
        run: |
          RELEASE_NAME=${{ steps.gen-release-info.outputs.release_name }}
          RELEASE_URL=${{ steps.create-release.outputs.url }}
          # See https://github.com/softprops/action-gh-release?tab=readme-ov-file#outputs
          RELEASE_APK_URL=${{ fromJSON(steps.create-release.outputs.assets)[0].browser_download_url }}
          # See:
          # https://open.larksuite.com/document/common-capabilities/message-card/message-cards-content/using-markdown-tags
          # for how to write content in feishu card.
          cat <<EOF > feishu_card.json
          {
            "msg_type": "interactive",
            "card": {
              "config": {
                "wide_screen_mode": true
              },
              "header": {
                "title": {
                  "tag": "plain_text",
                  "content": "IntelliMate 测试 APK 发布，版本：$RELEASE_NAME"
                }
              },
              "elements": [
                {
                  "tag": "div",
                  "text": {
                    "tag": "lark_md",
                    "content": "✅ 已上传至 Google Play Internal Testing 轨道\n📦 改动详见 [GitHub Release](${RELEASE_URL})\n📥 [Release APK 下载](${RELEASE_APK_URL})"
                  }
                }
              ]
            }
          }
          EOF
          curl -X POST ${{ secrets.FEISHU_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d @feishu_card.json
