name: Python Tests

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "**/*.py"
  #     - "requirements.txt"
  #     - ".github/workflows/ci.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      pgsql:
        image: pgvector/pgvector:pg16
        ports:
          - 15432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: sxwl666!
          POSTGRES_DB: inty_db

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Test Alembic versions
        run: |
          # Create a config.yaml file for alembic to reach the database:
          echo "database:" >> config.yaml
          echo "  db: inty_db" >> config.yaml
          echo "  host: localhost" >> config.yaml
          echo "  password: sxwl666!" >> config.yaml
          echo "  port: 15432" >> config.yaml
          echo "  user: postgres" >> config.yaml
          alembic upgrade head

      - name: Run tests
        run: |
          cp config.yaml.example config.yaml
          PYTHONPATH=$(pwd) pytest app/ -v --tb=short -s
