name: Build debug APK (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Create keystore.properties
      env:
        KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
      run: |
        echo "$KEYSTORE_PROPERTIES" > keystore.properties

    - name: Create Google Play service account key
      env:
        GOOGLE_PLAY_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "$GOOGLE_PLAY_SERVICE_ACCOUNT_KEY" > service-account-key.json

    - name: Build debug APK
      run: |
        ./gradlew assembleDebug --stacktrace --info
