# Update app/openapi.json when any of the app/api/v1/endpoints/ endpoint is changed.
name: Update openapi.json when endpoints are changed

on:
  push:
    branches:
      - main
    paths:
      - "app/api/v1/endpoints/**/*.py"
      - ".github/workflows/update_openapi_json.yaml"

env:
  PG_USER: postgres
  PG_PASSWORD: sxwl666!
  PG_DB: inty

jobs:
  update-openapi-json:
    runs-on: ubuntu-latest

    permissions:
      # Update file and commit
      contents: write
      pull-requests: write

    services:
      pgsql:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.PG_USER }}
          POSTGRES_PASSWORD: ${{ env.PG_PASSWORD }}
          POSTGRES_DB: ${{ env.PG_DB }}

    steps:
      - id: committer-token
        # https://github.com/marketplace/actions/create-github-app-token#use-app-token-with-actionscheckout
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.WORKFLOW_COMMITTER_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_COMMITTER_APP_SECRET }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.committer-token.outputs.token }}

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Based on https://adamj.eu/tech/2023/11/02/github-actions-faster-python-virtual-environments/
      - uses: actions/cache@v4
        with:
          path: .venv
          # Unique key for the cache
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
  
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt
          # https://stackoverflow.com/a/74669486
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

      - name: Update openapi.json
        run: |
          # Use dev environment config.yaml
          cp config.yaml.example config.yaml
          # docker compose up -d docker build caching is difficult to setup
          # so use start.sh directly to launch the server.
          ./start.sh &
          sleep 10
          curl http://localhost:8000/openapi.json | python -m json.tool >app/openapi.json

      - name: Create pull request if there are changes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          BRANCH_NAME="update-openapi-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME
          git add app/openapi.json
          git commit -m "Update openapi.json"
          git push origin HEAD:$BRANCH_NAME
          gh pr create --head $BRANCH_NAME --fill
